org.gradle.jvmargs=-Xmx4g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=true
MAPBOX_DOWNLOADS_TOKEN=sk.eyJ1IjoiNDlhcHAiLCJhIjoiY20xem83MGQ5MDg3aDJqczhhYnlmMGI1ZSJ9.8sYHBUyxYXncueYcckCBMg
android.disableResourceValidation=true
android.injected.testOnly=false
android.bundle.enableUncompressedNativeLibs=true
# Native 16 KB page size configuration
android.enableR8.fullMode=true
# 16 KB page size native alignment
android.ndkVersion=29.0.13113456
