// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1QP6tPVIeH617TLobf0Cj56yYBIE7ZcA',
    appId: '1:872417805780:android:59b36e9d636247af850241',
    messagingSenderId: '872417805780',
    projectId: 'app-af0a7',
    storageBucket: 'app-af0a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcLUPf0rh7vBTVxfUweafXv3sTDpOkWEo',
    appId: '1:872417805780:ios:8387aaae6d90f628850241',
    messagingSenderId: '872417805780',
    projectId: 'app-af0a7',
    storageBucket: 'app-af0a7.appspot.com',
    androidClientId: '872417805780-16bqk61d1vspkehfatdogbqaqpvhco3i.apps.googleusercontent.com',
    iosClientId: '872417805780-6ul51c5nsnl1nnahs9diudi7msr140cf.apps.googleusercontent.com',
    iosBundleId: 'com.example.fourtyninehub',
  );
}
