// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACecBTljJZl7XCzfDsaHjYDTMYcVULV9M',
    appId: '1:361206050719:android:8fd9d30d8e87729cab57aa',
    messagingSenderId: '361206050719',
    projectId: 'hub-bef9d',
    storageBucket: 'hub-bef9d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOSH2EShHg35-XYjvQVUkTFh9SdRdozu4',
    appId: '1:361206050719:ios:5dc195ff4b5ae685ab57aa',
    messagingSenderId: '361206050719',
    projectId: 'hub-bef9d',
    storageBucket: 'hub-bef9d.firebasestorage.app',
    iosBundleId: 'com.fourtyninehub.fourtynine',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyfzXIDNAv7BZPfpl7TSRRXBobOTpB5uQ',
    appId: '1:361206050719:web:d5915096706f01dbab57aa',
    messagingSenderId: '361206050719',
    projectId: 'hub-bef9d',
    authDomain: 'hub-bef9d.firebaseapp.com',
    storageBucket: 'hub-bef9d.firebasestorage.app',
    measurementId: 'G-Z75GECK5VG',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOSH2EShHg35-XYjvQVUkTFh9SdRdozu4',
    appId: '1:361206050719:ios:bba7653b728d6768ab57aa',
    messagingSenderId: '361206050719',
    projectId: 'hub-bef9d',
    storageBucket: 'hub-bef9d.firebasestorage.app',
    iosBundleId: 'com.fourtyninehub.fourtynine',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyfzXIDNAv7BZPfpl7TSRRXBobOTpB5uQ',
    appId: '1:361206050719:web:e9df38d8deacacc2ab57aa',
    messagingSenderId: '361206050719',
    projectId: 'hub-bef9d',
    authDomain: 'hub-bef9d.firebaseapp.com',
    storageBucket: 'hub-bef9d.firebasestorage.app',
    measurementId: 'G-0PHEQ83456',
  );

}