platform :ios, '14.0'
ENV['COCOAPODS_DISABLE_STATS'] = 'true'
$FirebaseSDKVersion = '11.10.0'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'podhelper')

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks! :linkage => :static
  use_modular_headers!
  # Explicit Firebase pods with version locking
  pod 'Firebase/CoreOnly', $FirebaseSDKVersion
  pod 'Firebase/Auth', $FirebaseSDKVersion
  pod 'Firebase/Messaging', $FirebaseSDKVersion


  # Required for proper header resolution
  pod 'Firebase', $FirebaseSDKVersion
  pod 'FirebaseCore', $FirebaseSDKVersion
  pod 'FirebaseCoreInternal', $FirebaseSDKVersion
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
#   flutter_install_all_ios_pods(File.dirname(File.realpath(__FILE__)))

  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
#     target.build_configurations.each do |config|
#       config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
#       config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
#       config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
#       config.build_settings['ENABLE_BITCODE'] = 'NO'
#       # Critical header paths
#       config.build_settings['HEADER_SEARCH_PATHS'] = [
#         '$(inherited)',
#         '"${PODS_ROOT}/Firebase/CoreOnly/Sources"',
#         '"${PODS_ROOT}/FirebaseCore/Sources"'
#       ]
#
#       # Workaround for module map issues
#       config.build_settings['OTHER_CFLAGS'] = ['-DFIREBASE_HAVE_MODULES']
#     end

    if target.name == 'deepar_flutter_plus'
      target.build_configurations.each do |config|
        config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
      end
    end
  end
end