source 'https://github.com/CocoaPods/Specs.git'
# source 'https://cdn.cocoapods.org/'
platform :ios, '14.0'

# Add Firebase modules explicitly
$FirebaseSDKVersion = '11.10.0'  # Match version from Podfile.lock

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks! :linkage => :static
  use_modular_headers!
  # Explicit Firebase dependencies
  pod 'Firebase/Core', $FirebaseSDKVersion
  pod 'Firebase/Auth', $FirebaseSDKVersion
  pod 'Firebase/Messaging', $FirebaseSDKVersion
  pod 'ZegoExpressEngine', :path => 'ZegoExpressEngine/'

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',
        'PERMISSION_CAMERA=1',
        'PERMISSION_MICROPHONE=1',
      ]
      # Exclude arm64 for simulator (optional, fixes Apple Silicon sim issues)
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'

      # Optional: skip embedding if needed
#       if target.name == 'deepar_flutter_plus'
#         config.build_settings['OTHER_LDFLAGS'] = '$(inherited) -framework "DeepAR"'
#         config.build_settings['FRAMEWORK_SEARCH_PATHS'] = [
#           '$(inherited)',
#           '$(PODS_ROOT)/deepar_flutter_plus/ios'
#         ]
#       end
    end
  end
end
