
import 'package:dartz/dartz.dart';
import 'package:fourtyninehub/features/RideFeature/data/models/ride_brand_model.dart';
import 'package:fourtyninehub/features/RideFeature/domain/entities/activity_trip_entity.dart';
import 'package:fourtyninehub/features/RideFeature/domain/entities/completed_trips_entity.dart';
import 'package:fourtyninehub/features/RideFeature/domain/entities/cost_per_km_entity.dart';
import 'package:fourtyninehub/features/RideFeature/domain/entities/dashboards/available_ride_trip_entity.dart';
import 'package:fourtyninehub/features/RideFeature/domain/entities/get_location_from_address_entity.dart';
import 'package:fourtyninehub/features/RideFeature/domain/entities/history_trip_for_rider_entity.dart';
import 'package:fourtyninehub/features/RideFeature/domain/entities/history_trip_for_user_entity.dart';
import 'package:fourtyninehub/features/RideFeature/domain/entities/car_years_and_types_entity.dart';
import 'package:fourtyninehub/features/RideFeature/domain/entities/check_driver_type_entity.dart';
import 'package:fourtyninehub/features/RideFeature/domain/entities/driver_info_entity.dart';
import 'package:fourtyninehub/features/RideFeature/domain/entities/driver_picture_optional_entity.dart';
import 'package:fourtyninehub/features/RideFeature/domain/entities/drivers_in_subcategory_entity.dart';
import 'package:fourtyninehub/features/RideFeature/domain/entities/expected_price_entity.dart';
import 'package:fourtyninehub/features/RideFeature/domain/entities/expected_price_params.dart';
import 'package:fourtyninehub/features/RideFeature/domain/entities/loading_info_entity.dart';
import 'package:fourtyninehub/features/RideFeature/domain/entities/loading_register_entity.dart';
import 'package:fourtyninehub/features/RideFeature/domain/entities/register_ride_not_special_entity.dart';
import 'package:fourtyninehub/features/RideFeature/domain/entities/register_ride_special_entity.dart';
import 'package:fourtyninehub/features/RideFeature/domain/entities/request_trip_params.dart';
import 'package:fourtyninehub/features/RideFeature/domain/entities/ride_brand_entity.dart';
import 'package:fourtyninehub/features/RideFeature/domain/entities/ride_category_entity.dart';
import 'package:fourtyninehub/features/RideFeature/domain/entities/ride_model_entity.dart';
import 'package:fourtyninehub/features/RideFeature/domain/entities/ride_offer_entity.dart';
import 'package:fourtyninehub/features/RideFeature/domain/entities/ride_request_trip_entity.dart';
import 'package:fourtyninehub/features/RideFeature/domain/entities/running_trips_entity.dart';
import 'package:fourtyninehub/features/RideFeature/domain/usecases/accept_trip_by_driver_use_case.dart';
import 'package:fourtyninehub/features/RideFeature/domain/usecases/cancel_pending_trip_by_client_use_case.dart';
import 'package:fourtyninehub/features/RideFeature/domain/usecases/cancel_trip_by_client.dart';
import 'package:fourtyninehub/features/RideFeature/domain/usecases/cancel_trip_by_rider.dart';
import 'package:fourtyninehub/features/RideFeature/domain/usecases/click_global_use_case.dart';
import 'package:fourtyninehub/features/RideFeature/domain/usecases/complete_trip_use_case.dart';
import 'package:fourtyninehub/features/RideFeature/domain/usecases/dashboards/watching_trips_usecase.dart';
import 'package:fourtyninehub/features/RideFeature/domain/usecases/get_all_activity_trips.dart';
import 'package:fourtyninehub/features/RideFeature/domain/usecases/get_all_completed_trips_use_case.dart';
import 'package:fourtyninehub/features/RideFeature/domain/usecases/get_all_history_trips_for_rider_use_case.dart';
import 'package:fourtyninehub/features/RideFeature/domain/usecases/get_all_running_trips_usecase.dart';
import 'package:fourtyninehub/features/RideFeature/domain/usecases/get_location_from_address_use_case.dart';
import 'package:fourtyninehub/features/RideFeature/domain/usecases/get_ride_categories_usecase.dart';
import 'package:fourtyninehub/features/RideFeature/domain/usecases/partial_payment_in_trip.dart';
import 'package:fourtyninehub/features/RideFeature/domain/usecases/recording_trip_use_case.dart';
import 'package:fourtyninehub/features/RideFeature/domain/usecases/rider_in_start_location_use_case.dart';
import 'package:fourtyninehub/features/RideFeature/domain/usecases/start_trip_use_case.dart';
import 'package:fourtyninehub/features/RideFeature/domain/usecases/update_driver_location_usecase.dart';
import 'package:fourtyninehub/features/RideFeature/domain/usecases/update_socket_location_usecase.dart';
import 'package:fourtyninehub/features/RideFeature/domain/usecases/update_trip_auto_accept_by_client_use_case.dart';
import 'package:fourtyninehub/features/RideFeature/domain/usecases/update_trip_price_from_client_use_case.dart';
import 'package:fourtyninehub/features/RideFeature/domain/entities/ride_color_entity.dart';
import 'package:fourtyninehub/features/RideFeature/domain/usecases/get_car_years_and_types_usecase.dart';
import 'package:fourtyninehub/features/RideFeature/domain/usecases/update_trip_price_use_case.dart';
import 'package:fourtyninehub/features/health_feature/create_doctor/domain/entities/governorate_entity.dart';
import 'package:fourtyninehub/features/RideFeature/domain/usecases/dashboards/get_available_ride_trips_use_case.dart';
import '../../../../core/error/failure.dart';
import 'package:fourtyninehub/features/RideFeature/domain/entities/driver_statistics_entity.dart';

import '../../../food_feature/restaurants_list/domain/entities/rate_response_entity.dart';
import '../../data/models/client/driver_all_rating_model.dart';
import '../entities/client/client_all_rating_entity.dart';
import '../entities/client/driver_all_rating_entity.dart';
import '../entities/create_no_track_trip_entity.dart';
import '../entities/dashboards/create_non_track_offer_entity.dart';
import '../entities/dashboards/update_driver_settings_entity.dart';
import '../entities/get_client_accepted_trips_entity.dart';
import '../entities/get_client_offer_trips_entity.dart';
import '../entities/get_client_past_trips_entity.dart';
import '../entities/get_client_pending_trips_entity.dart';
import '../entities/get_offers_entity.dart';
import '../usecases/accept_non_track_trip_use_case.dart';
import '../usecases/cancel_non_track_trip_use_case.dart';
import '../usecases/client_trips/get_driver_all_rating_use_case.dart';
import '../usecases/client_trips/update_client_rate_non_socket_use_case.dart';
import '../usecases/create_non_track_trip_use_case.dart';
import '../usecases/dashboards/add_rate_with_driver_use_case.dart';
import '../usecases/dashboards/create_non_track_offer_use_case.dart';
import '../usecases/dashboards/update_driver_settings_use_case.dart';
import '../usecases/get_client_pending_untracked_trips_use_case.dart';
import '../usecases/make_loading_request_trip_usecase.dart';
import '../usecases/make_non_tracking_request_trip_usecase.dart';

import '../../../account_taps/my_adds/domain/entity/click_entity.dart';
import '../usecases/rating_driver_by_client.dart';

abstract class RideRepository {

  /////////////////////////////////Nasr/////////////////////////////////

  Future<Either<Failure, RideCategoryEntityUpdated>> getRideCategories(GetRideCategoriesParams params);
  Future<Either<Failure, RideCategoryEntityUpdated>> getShippingCategories(GetRideCategoriesParams params);
  Future<Either<Failure, CheckDriverTypeEntity>> checkDriverType();
  Future<Either<Failure, bool>> registerRideNotSpecial(RegisterRideNotSpecialEntity params);
  Future<Either<Failure, bool>> loadingRegister(LoadingRegisterEntity params);
  Future<Either<Failure, LoadingInfoEntity>> getLoadingInfo(bool refresh);
  Future<Either<Failure, bool>> registerRideSpecial(RegisterRideSpecialEntity params);
  Future<Either<Failure, RideRequestTripEntity>> requestTrip(RequestTripUseCaseParams params);
  Future<Either<Failure, RideRequestTripEntity>> retrieveClientLatestTrip();
  Future<Either<Failure, RideRequestTripEntity>> acceptOfferByClient(String params);
  Future<Either<Failure, bool>> checkRealAmountEnough(double params);
  Future<Either<Failure, RideExpectedPriceEntity>> getExpectedPrice(RideExpectedPriceParams params);
  Future<Either<Failure, List<DriversInSubcategoryEntity>>> getDriversInSubcategory(String subCategoryId);
  Future<Either<Failure, RideDriverStatisticsEntity>> getDriverStatistics();
  Future<Either<Failure, bool>> deleteRideRegistration();
  Future<Either<Failure, List<RideBrandEntity>>> getRideBrands();
  Future<Either<Failure, CostPerKmEntity>> getCostPerKm();
  Future<Either<Failure, List<RideModelEntity>>> getRideModels(String brand);
  Future<Either<Failure, List<CarYearsAndTypesEntity>>> getCarYearsAndTypes(GetCarYearsAndTypesParams params);
  Future<Either<Failure, List<RideColorEntity>>> getRideCarColors();
  Future<Either<Failure, List<GovernorateEntity>>> getGovernorates();
  Future<Either<Failure, bool>> updateDriverLocation(UpdateDriverLocationUseCaseParams params);
  Future<Either<Failure, List<RunningTripsEntity>>> getAllRunningTrips(GetAllRunningTripsUseCaseParams params);
  Future<Either<Failure, List<CompletedTripsEntity>>> getAllCompletedTrips(GetAllCompletedTripsUseCaseParams params);
  Future<Either<Failure, GetLocationFromAddressEntity>> getLocationFromAddress(GetLocationFromAddressUseCaseParams params);
  Future<Either<Failure, bool>> acceptTripByDriver(AcceptTripByDriverUseCaseParams params);
  Future<Either<Failure, bool>> riderInStartLocation(RiderInStartLocationUseCaseParams params);
  Future<Either<Failure, bool>> startTrip(StartTripUseCaseParams params);
  Future<Either<Failure, bool>> partialPaymentInTrip(PartialPaymentInTripUseCaseParams params);
  Future<Either<Failure, bool>> completeTrip(CompleteTripUseCaseParams params);
  Future<Either<Failure, bool>> cancelTripByRider(CancelTripByRiderUseCaseParams params);
  Future<Either<Failure, bool>> finalizeTripByRider(String params);
  Future<Either<Failure, bool>> cancelTripByClient(CancelTripByClientUseCaseParams params);
  Future<Either<Failure, bool>> cancelPendingTripByClient(CancelPendingTripByClientUseCaseParams params);
  Future<Either<Failure, bool>> recordingTrip(RecordingTripUseCaseParams params);
  Future<Either<Failure, bool>> updateTripAutoAcceptByClient(UpdateTripAutoAcceptByClientUseCaseParams params);
  Future<Either<Failure, bool>> makeRequestTrip();
  Future<Either<Failure, bool>> makeNonTrackingRequestTrip(MakeNonTrackingRequestTripUsecaseParam params);
  Future<Either<Failure, bool>> makeLoadingRequestTrip(MakeLoadingRequestTripUsecaseParam params);
  Future<Either<Failure, bool>> updateTripPriceFromClient(UpdateTripPriceFromClientUseCaseParams params);
  Future<Either<Failure, bool>> updateTripPrice(UpdateTripPriceUseCaseParams params);
  Future<Either<Failure, ActivityTripEntity>> getAllActivityTrips(GetAllActivityTripsUseCaseParams params);
  Future<Either<Failure, List<HistoryTripForUserEntity>>> getAllHistoryTripsForUser();
  Future<Either<Failure, GetOffersResponseEntity>> getClientOffers();
  Future<Either<Failure, GetOffersResponseEntity>> getLoadingOffers();
  Future<Either<Failure, List<HistoryTripForRiderEntity>>> getAllHistoryTripsForRider(GetAllHistoryTripsForRiderUseCaseParams params);
  Future<Either<Failure, DriverInfoEntity>> getRideDriverInfo(bool refresh);
  Future<Either<Failure, DriverPictureOptionalEntity>> getDriverPictureOptional();
  Future<Either<Failure, List<AvailableRideTripEntity>>> getAvailableRideTrips(AvailableRideTripsUseCaseParams params);
  void listenToRideOffers(Function(RideOfferEntity offer) params);
  void listenToOfferUpdateUntrackedTrip(Function(ClientOfferTripEntity offer) params);
  Future<Either<Failure, bool>> listenToUpdateLocation(UpdateSocketLocationParams params);
  Future<Either<Failure, bool>> emitWatchingTrips(WatchingTripsParams params);
  Future<Either<Failure, ClickEntity>> click(ClickParams params);
  Future<Either<Failure, CreateNonTrackTripEntity>> createNonTrackTrip(CreateNonTrackTripParams params);
  Future<Either<Failure, CreateNonTrackTripEntity>> cancelNonTrackTrip(CancelNonTrackTripParams params);
  Future<Either<Failure, CreateNonTrackTripEntity>> acceptNonTrackTrip(AcceptNonTrackTripParams params);
  Future<Either<Failure, CreateNonTrackTripEntity>> refuseNonTrackTrip(AcceptNonTrackTripParams params);
  Future<Either<Failure, CreateNonTrackOfferEntity>> createNonTrackOffer(CreateNonTrackOfferParams params);
  Future<Either<Failure, UpdateDriverSettingsEntity >> updateDriverSettings(UpdateDriverSettingsParams params);
  Future<Either<Failure, List<ClientPendingTripEntity>>> getClientPendingUntrackedTrips({required ClientPendingTripParams params});
  Future<Either<Failure, List<ClientAcceptedTripEntity>>> getClientAcceptedUntrackedTrips({required ClientPendingTripParams params});
  Future<Either<Failure, List<ClientOfferTripEntity>>> getClientOfferUntrackedTrips({required ClientPendingTripParams params});
  Future<Either<Failure, List<ClientPastTripEntity >>> getClientPastUntrackedTrips({required ClientPendingTripParams params});
  Future<Either<Failure, bool>> sendOkIamComing();
  Future<Either<Failure, bool>> ratingDriverByClient(RatingDriverByClientUseCaseParams params);
  Future<Either<Failure, RateResponseEntity>> addRateWithClient(AddRateWithDriverParams params);
  Future<Either<Failure, CreateNonTrackTripEntity>> updateClientRateNonSocket(UpdateClientRateParams params);
  Future<Either<Failure, DriverAllRatingEntity >> getDriverAllRating(DriverAllRatingParams params);
  Future<Either<Failure, ClientAllRatingEntity >> getClientAllRating(DriverAllRatingParams params);

}