import 'package:dartz/dartz.dart';
import 'package:fourtyninehub/features/RideFeature/domain/entities/dashboards/accept_offer_entity.dart';
import 'package:fourtyninehub/features/RideFeature/domain/entities/dashboards/arrived_to_client_entity.dart';
import 'package:fourtyninehub/features/RideFeature/domain/entities/dashboards/available_ride_trip_entity.dart';
import 'package:fourtyninehub/features/RideFeature/domain/entities/dashboards/emergency_contact_entity.dart';
import 'package:fourtyninehub/features/RideFeature/domain/entities/dashboards/running_trip_entity.dart';
import 'package:fourtyninehub/features/RideFeature/domain/entities/dashboards/support_details_entity.dart';
import 'package:fourtyninehub/features/RideFeature/domain/entities/dashboards/update_trip_auto_accept_entity.dart';
import 'package:fourtyninehub/features/RideFeature/domain/entities/dashboards/update_trip_price_entity.dart';
import 'package:fourtyninehub/features/RideFeature/domain/usecases/dashboards/complete_ride_trip_with_price_usecase.dart';
import 'package:fourtyninehub/features/RideFeature/domain/usecases/dashboards/driver_rate_client_usecase.dart';
import 'package:fourtyninehub/features/RideFeature/domain/usecases/dashboards/emergency_support_usecase.dart';
import 'package:fourtyninehub/features/RideFeature/domain/usecases/dashboards/get_past_trips_usecase.dart';
import 'package:fourtyninehub/features/RideFeature/domain/usecases/dashboards/get_support_details_usecase.dart';
import 'package:fourtyninehub/features/RideFeature/domain/usecases/dashboards/start_ride_trip_usecase.dart';
import 'package:fourtyninehub/features/new_trip_join/domain/entities/my_booking_entity.dart';
import 'package:fourtyninehub/features/new_trip_join/domain/usecases/client/listen_to_update_location_driver_use_case.dart';
import 'package:fourtyninehub/features/new_trip_join/domain/usecases/driver/listen_to_client_coming_use_case.dart';
import 'package:fourtyninehub/features/new_trip_join/domain/usecases/listen_to_cancel_route_use_case.dart';

import '../../../../core/error/failure.dart';
import '../../../food_feature/restaurants_list/domain/entities/rate_response_entity.dart';
import '../../data/models/loading/get_loading_accepted_model.dart';
import '../entities/dashboards/create_non_track_offer_entity.dart';
import '../entities/dashboards/driver_settings_entity.dart';
import '../entities/dashboards/get_accepted_ride_non_socket_trip_entity.dart';
import '../entities/dashboards/get_available_ride_non_socket_trip_entity.dart';
import '../entities/dashboards/get_past_ride_non_socket_trip_entity.dart';
import '../entities/dashboards/settings_dashboard_entity.dart';
import '../entities/dashboards/trips_response_entity.dart';
import '../entities/loading/get_loading_avaliable_entity.dart';
import '../entities/loading/get_loading_history_entity.dart';
import '../entities/loading/settings_driver_loading_entity.dart';
import '../usecases/client_trips/update_client_rate_non_socket_use_case.dart';
import '../usecases/dashboards/add_rate_with_driver_use_case.dart';
import '../usecases/dashboards/create_driver_rating_usecase.dart';
import '../usecases/dashboards/create_new_offer_dashboard_usecase.dart';
import '../usecases/dashboards/create_non_track_offer_use_case.dart';
import '../usecases/dashboards/get_available_ride_trips_use_case.dart';
import '../usecases/dashboards/loading/create_rate_with_driver_loading_use_case.dart';
import '../usecases/dashboards/loading/update_driver_loading_settings_use_case.dart';
import '../usecases/dashboards/update_settings_dashboard_usecase.dart';
import '../usecases/get_client_pending_untracked_trips_use_case.dart';

abstract class TripRepository {
   Future<Either<Failure, TripsResponseEntity>> getAvailableTrips(AvailableRideTripsUseCaseParams params);
   Future<Either<Failure, SupportDetailsEntity>> getSupportDetails(GetSupportDetailsParams params);
   Future<Either<Failure, List<AvailableRideNonSocketTripEntity>>> getAvailableNonSocketTrips(ClientPendingTripParams params);
   Future<Either<Failure, List<AcceptedRideNonSocketTripEntity >>> getAcceptedNonSocketTrips(ClientPendingTripParams params);
   Future<Either<Failure, List<HistoryTripEntity  >>> getPastNonSocketTrips(ClientPendingTripParams params);
   Future<Either<Failure, TripsResponseEntity>> getPastTrips(GetPastTripsParams params);
   Future<Either<Failure, List<EmergencyContactEntity>>> getEmergencyContacts();
   Future<Either<Failure, EmergencyContactEntity>> addEmergencyContacts(EmergencyContactEntity params);
   Future<Either<Failure, bool>> deleteEmergencyContact(EmergencyContactEntity params);
   Future<Either<Failure, EmergencyContactEntity>> editEmergencyContacts(EmergencyContactEntity params);
   Future<Either<Failure, SettingsDashboardEntityResponse>> getSettings();
   Future<Either<Failure, DriverSettingsEntity >> getDriverSettings();
   Future<Either<Failure, bool>> updateSettings(UpdateSettingsDashboardUsecaseParam params);
   Future<Either<Failure, bool>> createNewOffer(CreateNewOfferDashboardUsecaseParam params);
   Future<Either<Failure, bool>> createNewOfferNonSocket(CreateNewOfferDashboardUsecaseParam params);
   Future<Either<Failure, bool>> createDriverRating(CreateUpdateDriverRatingUsecaseParam params);
   Future<Either<Failure, bool>> updateDriverRating(CreateUpdateDriverRatingUsecaseParam params);
   Future<Either<Failure, bool>> acceptTrip(String params);
   Future<Either<Failure, RunningTripEntity>> getRunningTrip();
   Future<Either<Failure, RunningTripEntity>> goingToClient(String id);
   Future<Either<Failure, bool>> driverRateClient(DriverRateClientParams id);
   Future<Either<Failure, bool>> updateDriverRateClient(DriverRateClientParams id);
   Future<Either<Failure, bool>> arrivedToClient(ArrivedToClientEntity params);
   Future<Either<Failure, bool>> emergencySupport(EmergencySupportParams params);
   Future<Either<Failure, String>> startDriverTrip(StartDriverTripParams params);
   Future<Either<Failure, bool>> completeDriverTrip(StartDriverTripParams params);
   Future<Either<Failure, bool>> completeDriverTripWithRemainingMoney(CompleteDriverTripWithRemainingMoneyParams params);
   Future<Either<Failure, RateResponseEntity>> addRateWithDriver(AddRateWithDriverParams params);
   Future<Either<Failure, RateResponseEntity>> addRateWithDriverLoading(AddRateWithDriverLoadingParams params);
   Future<Either<Failure, RateResponseEntity>> addRateWithClientLoading(AddRateWithDriverLoadingParams params);
   void listenToUpdateTripAutoAccept(Function(UpdateTripAutoAcceptEntity trip) params);
   void listenToUpdateTripPrice(Function(UpdateTripPriceEntity trip) params);
   void listenToNewTrip(Function(AvailableRideTripEntity trip) params);
   void listenToRemoveTrip(Function(String tripId) params);
   void listenToClientComing(Function(String tripId) params);
   void listenToEndTrip(Function(String tripId) params);
   void listenToRemoveUntrackedTrip(Function(String tripId) params);
   void listenToRemoveOffer(Function(String tripId) params);
   void listenToRemoveLoading(Function(String tripId) params);
   void listenToAcceptOffer(Function(AcceptOfferEntity trip) params);
   void listenToAcceptUntrackedTripOffer(Function(String tripId) params);
   void listenToAcceptLoadingTripOffer(Function(String tripId) params);
   void listenToRemoveAcceptedLoadingTripOffer(Function(String tripId) params);
   void listenToAvailableUntrackedTrip(Function(AvailableRideNonSocketTripEntity trip) params);
   void listenToAvailableLoading(Function(GetLoadingAvailableEntity trip) params);
   void listenToPartialPaymentDriver(Function(num amountPaidCash) params);
   void listenToCancelRoute(Function(ListenToCancelRouteParams params) params);
   void listenToUpdateRoute(Function(MyBookingEntity route) params);
   void listenToAcceptRoute(Function(MyBookingEntity route) params);
   void listenToNewRoute(Function(MyBookingEntity newBooking) params);
   void listenToDriverTheOnWay(Function(MyBookingEntity newBooking) params);
   void listenToNewRouteDriver(Function(MyBookingEntity newBooking) params);
   void listenToComingClient(Function(ListenToClientComingParams params) params);
   void listenToDriverArrived(Function(String waitingTime) params);
   void listenToRouteCancelled(Function(String message) params);
   void listenToDriverOnTheWay(Function(String message) params);
   void listenToTripAccept(Function(String message) params);
   void listenToUpdateLocationDriver(Function(UpdateLocationDriverParams params) params);
   void listenToDriverNoShowClient(Function(String waitingTime) params);
   void listenToPassengerPickedUp(Function(String message) params);
   void listenToJoinAvailableRoutes(Function(bool isJoined) params);
   void listenToLeaveAvailableRoutes(Function(String routeId) params);
   Future<Either<Failure, List<GetLoadingAcceptedEntity>>> getAcceptedNonSocketLoading(ClientPendingTripParams params);
   Future<Either<Failure, List<GetLoadingAvailableEntity>>> getAvailableNonSocketLoading(ClientPendingTripParams params);
   Future<Either<Failure, List<GetLoadingHistoryEntity>>> getHistoryNonSocketLoading(ClientPendingTripParams params);
   Future<Either<Failure, CreateNonTrackOfferEntity>> createOfferLoading(CreateNonTrackOfferParams params);
   Future<Either<Failure, CreateNonTrackOfferEntity>> updateDriverRateNonSocket(UpdateClientRateParams params);
   Future<Either<Failure, CreateNonTrackOfferEntity>> updateDriverRateLoadingNonSocket(UpdateClientRateParams params);
   Future<Either<Failure, DriverSettingLoadingEntity >> getDriverLoadingSettings();
   Future<Either<Failure, CreateNonTrackOfferEntity >> updateDriverLoadingSettings(UpdateDriverSettingsLoadingParams params);


}