// DO NOT EDIT. This is code generated via package:easy_localization/generate.dart

// ignore_for_file: prefer_single_quotes, avoid_renaming_method_parameters

import 'dart:ui';

import 'package:easy_localization/easy_localization.dart' show AssetLoader;

class CodegenLoader extends AssetLoader{
  const CodegenLoader();

  @override
  Future<Map<String, dynamic>?> load(String path, Locale locale) {
    return Future.value(mapLocales[locale.toString()]);
  }

  static const Map<String,dynamic> ar = {
  "join": "انضم الآن",
  "arabic": "اللغه العربيه",
  "english": "اللغه الانجليزيه",
  "newMeeting": "اجتماع جديد",
  "meal": "اكله",
  "darkMode": "الوضع الداكن",
  "lightMode": "الوضع الفاتح",
  "voice": "صوت",
  "meet": "زوم",
  "cast": "سرعة",
  "tweet": "تويته",
  "reels": "بكرات",
  "chat": "شات",
  "find": "ايجاد",
  "live": "لابف",
  "health": "صحه",
  "ship": "تحميله",
  "ride": "توصيله",
  "lang": "E",
  "search": "بحث",
  "ads": "اعلانات",
  "ad": "اعلان",
  "wallet": "محفظه",
  "gift": "هدايا",
  "balance": "رصيد",
  "pickMe": "وصلني معاك",
  "tripJoin": "جاي معاك",
  "auction": "مزاد",
  "installments": "تقسيط",
  "craft": "حرفه",
  "homeService": "خدمه منزليه",
  "homeEssentials": "مستلزمات منزل",
  "scenery": " ديكور",
  "specialities": "التخصصات",
  "medicalService": "الخدمات الطبية",
  "doctor": "دكتور",
  "doctors": "دكاتره",
  "call": "الاتصال",
  "clinicVisit": "زيارة العيادة",
  "emergency": "الطوارئ",
  "homeVisit": "زيارة منزلية",
  "firstName": "الاسم الأول",
  "phoneNumber": "رقم الهاتف",
  "speciality": "التخصص",
  "address": "العنوان",
  "confirm": "تاكيد",
  "doctorList": "قائمة الأطباء",
  "noDoctorsFound": "لم يتم العثور على أطباء",
  "governorate": "المحافظة",
  "city": "المدينة",
  "emptyFieldNotValid": "حقل فارغ غير صالح",
  "login": "تسجيل الدخول",
  "register": "تسجيل",
  "emailOrPhone": "البريد الإلكتروني أو الهاتف",
  "password": "كلمة المرور",
  "forgetPassword": "نسيت كلمة المرور",
  "lastName": "اللقب",
  "gender": "الجنس",
  "code": "رمز الإحالة (اختياري)",
  "female": "أنثى",
  "male": "ذكر",
  "conditions": "الشروط والأحكام",
  "iAcceptAll": "أوافق على جميع",
  "terms": "يرجى قبول الشروط والأحكام للمواصلة.",
  "advertiseYourCompany": "أعلن عن شركتك",
  "quraan": "القرآن الكريم",
  "azkar": "الأذكار",
  "favouriteCategories": "الفئات المفضلة",
  "favouriteSubCategories": "الفئات الفرعية المفضلة",
  "favouriteAds": "الإعلانات المفضلة",
  "requestHistory": " سجل الطلبات",
  "lists": "القوائم",
  "myAds": "إعلاناتي",
  "settings": "الإعدادات",
  "privacy": "الخصوصية",
  "policies": "السياسات",
  "shareApp": "مشاركة التطبيق",
  "contactUs": "اتصل بنا",
  "logout": "تسجيل الخروج",
  "luckyWheel": "عجلة الحظ",
  "feelLucky": "هل تشعر بالحظ؟",
  "restaurants": "مطعم",
  "meals": "وجبات الطعام",
  "message": "رسالة",
  "photo": "صورة",
  "video": "فيديو"
};
static const Map<String,dynamic> en = {
  "join": "Join",
  "arabic": "Arabic",
  "english": "English",
  "newMeeting": "New Meeting",
  "meal": "Meal",
  "darkMode": "Dark mode",
  "lightMode": "Light mode",
  "voice": "Voice",
  "meet": "Meet",
  "cast": "Cast",
  "tweet": "Tweet",
  "reels": "Reels",
  "chat": "Chat",
  "find": "Find",
  "live": "Live",
  "health": "Health",
  "ship": "Ship",
  "ride": "Ride",
  "lang": "ع",
  "search": "Search",
  "ads": "Ads",
  "ad": "Ad",
  "wallet": "Wallet",
  "gift": "Gift",
  "balance": "Balance",
  "pickMe": "Pick Me",
  "tripJoin": "Trip Join",
  "auction": "Auction",
  "installments": "Installments",
  "craft": "Craft",
  "homeService": "Home Service",
  "homeEssentials": "Home Essentials",
  "scenery": "Scenery",
  "specialities": "Specialities",
  "medicalService": "Medical Service",
  "doctor": "Doctor",
  "doctors": "Doctors",
  "call": "Call",
  "clinicVisit": "Clinic Visit",
  "emergency": "Emergency",
  "homeVisit": "Home Visit",
  "firstName": "First Name",
  "phoneNumber": "Phone Number",
  "speciality": "Speciality",
  "address": "Address",
  "confirm": "Confirm",
  "doctorList": "Doctor List",
  "noDoctorsFound": "No doctors found",
  "governorate": "Governorate",
  "city": "City",
  "emptyFieldNotValid": "Empty Field Not Valid",
  "login": "Login",
  "register": "Register",
  "emailOrPhone": "Email Or Phone",
  "password": "Password",
  "forgetPassword": "Forget Password",
  "lastName": "Last Name",
  "gender": "Gender",
  "code": "Referral Code(Optional)",
  "female": "Female",
  "male": "Male",
  "conditions": "Terms,Rules & Conditions",
  "iAcceptAll": "I Accept All",
  "terms": "Please accept the terms and conditions to continue.",
  "message": "Message",
  "photo": "Photo",
  "video": "Video",
  "advertiseYourCompany": "Advertise Your Company",
  "quraan": "Quraan",
  "azkar": "Azkar",
  "favouriteCategories": "Favourite Categories",
  "favouriteSubCategories": "Favourite Sub Categories",
  "favouriteAds": "Favourite Ads",
  "requestHistory": "Requests History",
  "lists": "Lists",
  "myAds": "My Ads",
  "settings": "Settings",
  "privacy": "Privacy",
  "policies": "Policies",
  "shareApp": "Share App",
  "contactUs": "Contact Us",
  "logout": "logout",
  "luckyWheel": "Lucky Wheel",
  "feelLucky": "Do You feel lucky?",
  "restaurants": "Restaurants",
  "meals": "Meals"
};
static const Map<String, Map<String,dynamic>> mapLocales = {"ar": ar, "en": en};
}
