// DO NOT EDIT. This is code generated via package:easy_localization/generate.dart

// ignore_for_file: prefer_single_quotes, avoid_renaming_method_parameters

import 'dart:ui';

import 'package:easy_localization/easy_localization.dart' show AssetLoader;

class CodegenLoader extends AssetLoader{
  const CodegenLoader();

  @override
  Future<Map<String, dynamic>?> load(String path, Locale locale) {
    return Future.value(mapLocales[locale.toString()]);
  }

  static const Map<String,dynamic> ar = {
  "nnew": "جديد",
  "today": "اليوم",
  "tommorow": "غدًا",
  "meeting": "اجتماع",
  "join": "انضمام",
  "schedule": "جدولة",
  "scheduleAMeeting": "جدولة اجتماع",
  "startDateBeginValidation": "يجب أن تكون تاريخ البدء قبل تاريخ الانتهاء",
  "startDateTimeValidation": "يجب أن يكون تاريخ البدء في المستقبل",
  "pleaseFillAllFields": "اكمل البيانات من فضلك",
  "availableTrips": "الرحلات المتاحه",
  "done": "تم",
  "date": "التاريخ",
  "selectADate": "اختر تاريخًا",
  "from": "من",
  "to": "إلى",
  "share": "مشاركة",
  "screen": "شاشة",
  "addAcalender": "أضف جدولك",
  "meetingId": "رمز الاجتماع:",
  "startNow": "ابدأ الآن",
  "emptyMeetingIdValidator": "يرجى إدخال نص:",
  "invalidInputValidator": "إدخال غير صالح: مسموح فقط بالأرقام و / و .",
  "meetingMustBe8Characters": "يجب أن يتكون رمز الاجتماع من 8 أرقام",
  "joinMeeting": "الانضمام إلى الاجتماع",
  "joinMeetingWithShareScreen": "الانضمام إلى اجتماع مع مشاركة الشاشة",
  "joinMeetingWithId": "الانضمام إلى الاجتماع برمز:",
  "addTopic": "أضف موضوعًا",
  "addLiveGoal": "أهدافك",
  "startAMeeting": "ابدأ الاجتماع",
  "faceBeautification": "تجميل الوجه",
  "goLive": "ابدأ البث المباشر",
  "usePersonalMeetingId": "استخدم معرف الاجتماع الشخصي",
  "videoOn": "الدخول بواسطه الفيديو",
  "mute": "كتم الصوت",
  "unmute": "تفعيل الصوت",
  "startVideo": "تشغيل الفيديو",
  "stopVideo": "فيديو",
  "participants": "المشاركون",
  "whiteBoard": "السبورة البيضاء",
  "roomCode": "رمز الغرفة",
  "copiedSuccessfully": "تم النسخ بنجاح",
  "saySomthing": "...قل شيئًا",
  "end": "إنهاء",
  "leave": "مغادرة",
  "EndMeetingForAll": "إنهاء الاجتماع للجميع",
  "leaveMeeting": "مغادرة الاجتماع",
  "live": "مباشر",
  "clubVoice": "نادي صوتي",
  "roomSubject": "موضوع الغرفة",
  "pleaseEnterSimpleSubject": "يرجى إدخال وصف بسيط",
  "enterRoomSubject": "أدخل موضوع الغرفة",
  "roomSubjectValidation": "لا يمكن أن يكون موضوع الغرفة فارغًا",
  "createRoom": "إنشاء غرفة",
  "audience": "الجمهور",
  "voiceChanging": "تغيير الصوت",
  "reverb": "الصدى",
  "meetingTitle": "عنوان الاجتماع",
  "audioEffects": "التأثيرات الصوتيه",
  "arabic": "اللغه العربيه",
  "english": "اللغه الانجليزيه",
  "newMeeting": "اجتماع جديد",
  "meal": "اكله",
  "darkMode": "الوضع الداكن",
  "lightMode": "الوضع الفاتح",
  "voice": "صوت",
  "meet": "اجتماع",
  "cast": "سرعة",
  "noRooms": "لا توجد غرف صوتيه",
  "selectATopic": "اختر الموضوع",
  "editYourLiveGoal": "أضف اهداف البث",
  "goalExpirationIn4Hours": "أهداف البث متاحه لمده 4 ساعات",
  "describeYourGoal": "اكتب رساله تشجيعيه ",
  "progress": "تم:",
  "gifts": "هدايا",
  "goalsAreSelectedSuccess": "تم اختيار الاهداف",
  "restaurantName": "إسم المطعم",
  "restaurantNumber": "رقم المطعم",
  "theCommercialRegister": "السجل التجاري",
  "theApplicationDoesNotDeductAnyPercentageFromTheServiceProvider": "التطبيق لا يخصم اي نسبه من مزود الخدمة",
  "youWillGetEGP3650PerYearIfYouSubscribeDaily": "سوف تحصل على 3650 جنيها في السنه عندما تشترك يوميا",
  "welcomeToResturantRegisteration": "مرحبا بك في تسجيل المطعم",
  "selecteSubcategory": "اختر الفئه الفرعيه:",
  "photoForRestaurant": "صور للمطعم",
  "searchForFavouriteMeals": "",
  "firstPage": "الصفحه الأولى",
  "secondPage": "الصفحه الثانيه",
  "thirdPage": "الصفحه الثالثه",
  "selectGovernorate": "اختر المحافظه",
  "selectCity": "اختر المدينه",
  "newBookingsAreWaitingYouGoToResturantDashboardAndExploreMore": "الحجوزات الجديدة في الانتظار، سوف تذهب للركاب وتصفح المزيد.",
  "premium": "العروض الخاصه",
  "comma": "،",
  "noResultFound": "لايوجد نتائج",
  "restaurantDashboard": "لوحة المطعم",
  "allRestaurants": "كل المطاعم",
  "restaurantsForSelectedMeal": "المطاعم لهذه الوجبه",
  "itemName": "اسم الوجبة",
  "price": "السعر",
  "salary": "المرتب",
  "youHaveSubmittedYourRegistrationSuccessfullyWaitingForAdministrationApproval": "تم تقديم التسجيل بنجاح، الان يتم الموافقة عليها من قبل المشرف",
  "selectSubcategoryFirst": "يرجى تحديد الفئه الفرعيه",
  "uploadingImage": "جاري تحميل الصورة...",
  "cantLoadCities": "لا يمكن تحميل المدن",
  "cantLoadGovernorates": "لا يمكن تحميل المحافظات",
  "cantLoadSubCategories": "لا يمكن تحميل الفئات الفرعية",
  "cantLoadRestaurants": "لا يمكن تحميل المطاعم",
  "cantLoadMainCategories": "لا يمكن تحميل الفئات الرئيسية",
  "cantLoadCategories": "لا يمكن تحميل الفئات",
  "cantLoadSpecialities": "لا يمكن تحميل الاختصاصات",
  "cantLoadSubSubCategories": "لا يمكن تحميل الفئات الفرعية الفرعية",
  "creatingRestaurant": "جاري انشاء المطعم...",
  "youCanEnjoyServingYourClintsUsingYourRestaurantByClickingOnTheRigesterButtonAbove": "يمكنك الاستمتاع بخدمة عملائك باستخدام مطعمك بالضغط على زر التسجيل بالأعلى.",
  "photoForMeal": "صور للوجبة",
  "menu": "القائمة",
  "submit": "ارسال",
  "needToLogin": "يجب عليك تسجيل الدخول",
  "completeAllFields": "يرجى تحديد جميع الحقول",
  "tweet": "تغريدة",
  "reels": "ريلز",
  "chat": "دردشة",
  "find": "اكتشف",
  "health": "صحه",
  "ship": "تحميله",
  "ride": "توصيله",
  "lang": "E",
  "ad": "اعلان",
  "ads": "اعلانات",
  "wallet": "محفظه",
  "gift": "هدايا",
  "balance": "رصيد",
  "pickMe": "وصلني معاك",
  "tripJoin": "جاي معاك",
  "auction": "مزاد",
  "installments": "تقسيط",
  "homeService": "خدمه منزليه",
  "homeEssentials": "مستلزمات منزل",
  "specialities": "التخصصات",
  "medicalService": "الخدمات الطبية",
  "doctor": "دكتور",
  "doctors": "دكاتره",
  "call": "الاتصال",
  "clinicVisit": "زيارة العيادة",
  "emergency": "الطوارئ",
  "homeVisit": "زيارة منزلية",
  "firstName": "الاسم الأول",
  "phoneNumber": "رقم الهاتف",
  "speciality": "التخصص",
  "address": "العنوان",
  "confirm": "تاكيد",
  "doctorList": "قائمة الأطباء",
  "noDoctorsFound": "لم يتم العثور على أطباء",
  "governorate": "المحافظة",
  "city": "المدينة",
  "emptyFieldNotValid": "حقل فارغ غير صالح",
  "login": "تسجيل الدخول",
  "register": "تسجيل",
  "emailOrPhone": "البريد الإلكتروني أو الهاتف",
  "password": "كلمة المرور",
  "forgetPassword": "نسيت كلمة المرور",
  "lastName": "اللقب",
  "gender": "الجنس",
  "code": "رمز الإحالة (اختياري)",
  "female": "أنثى",
  "male": "ذكر",
  "conditions": "الشروط والأحكام",
  "iAcceptAll": "أوافق على جميع",
  "terms": "يرجى قبول الشروط والأحكام للمواصلة.",
  "advertiseYourCompany": "أعلن عن شركتك",
  "quraan": "القرآن الكريم",
  "azkar": "الأذكار",
  "favouriteCategories": "الفئات المفضلة",
  "favouriteSubCategories": "الفئات الفرعية المفضلة",
  "favouriteAds": "الإعلانات المفضلة",
  "requestHistory": " سجل الطلبات",
  "lists": "القوائم",
  "myAds": "إعلاناتي",
  "settings": "الإعدادات",
  "somethingWentWrong": "حدث خطأ ما",
  "privacy": "الخصوصية",
  "policies": "السياسات",
  "shareApp": "مشاركة التطبيق",
  "contactUs": "اتصل بنا",
  "logout": "تسجيل الخروج",
  "luckyWheel": "عجلة الحظ",
  "feelLucky": "هل تشعر بالحظ؟",
  "restaurants": "مطعم",
  "meals": "وجبات الطعام",
  "message": "رسالة",
  "photo": "صورة",
  "video": "فيديو",
  "openAppSettings": "فتح إعدادات التطبيق",
  "allowAccessToYourCamera": "السماح بالوصول للكاميرا",
  "allowAccessToYourMicrophone": "السماح بالوصول للميكروفون",
  "document": "مستند",
  "camera": "كاميرا",
  "microphone": "ميكروفون",
  "gallery": "المعرض",
  "audio": "الصوت",
  "location": "الموقع",
  "contact": "جهة اتصال",
  "pickPhotoOrVideo": "اختر صورة او فيديو",
  "noRideSubcategories": "لا توجد فئات فرعية",
  "enableNotifications": "تفعيل الإشعارات",
  "changePassword": "تغيير كلمة المرور",
  "disableAccount": "تعطيل الحساب",
  "deleteAccount": "حذف الحساب",
  "alert": "تنبيه!",
  "disable": "هل أنت متأكد من أنك تريد تعطيل حسابك؟",
  "delete": "هل أنت متأكد من أنك تريد حذف حسابك؟",
  "specialAds": "إعلانات خاصة",
  "friends": "الأصدقاء",
  "Doctor": "طبيب",
  "loadingDriver": "سائق نقل",
  "Restaurant": "مطعم",
  "driver": "سائق",
  "sureLogout": "هل أنت متأكد أنك تريد تسجيل الخروج؟",
  "no": "لا",
  "welcomeBack": "مرحبًا بعودتك",
  "oTP": "تم إرسال OTP بنجاح",
  "required": "مطلوب",
  "emailFormat": "أدخل تنسيق البريد الإلكتروني الصحيح",
  "email": "البريد الإلكتروني",
  "typeHere": "اكتب هنا",
  "sendOTP": "أرسل OTP",
  "forget": "نسيت كلمة المرور",
  "verify": "التحقق",
  "emailOtp": "إرسال OTP عبر البريد الإلكتروني",
  "verification": "التحقق",
  "notifications": "الإشعارات",
  "checkVerification": "يرجى التحقق من بريدك الإلكتروني لمعرفة رمز التحقق",
  "congratulations": "تهانينا",
  "close": "إغلاق",
  "giftApp": "لقد حصلت على هدية بقيمة 400 جنيه كهدية ترحيبية للتسجيل في تطبيق 49.",
  "clearAll": "حذف الكل",
  "clearNotification": "هل أنت متأكد من أنك تريد مسح جميع الإشعارات؟",
  "showNotification": "هل أنت متأكد من أنك تريد قراءه جميع الإشعارات؟",
  "clearNoti": "هل أنت متأكد أنك تريد مسح هذا الإشعار؟",
  "ok": "نعم",
  "cancel": "الغاء",
  "winners": "الفائزون",
  "competition": "المسابقات",
  "count": "العدد: ",
  "max": "الحد الأقصى: ",
  "money": "اموال",
  "points": "نقاط",
  "notEnoughWheel": "لا يوجد عدد كاف من العناصر لتدوير العجلة",
  "spin": "دوران",
  "companyAdvertise": "اعلان شركه",
  "textOnly": "نص فقط",
  "createTextPost": "إنشاء منشور نصي",
  "pictureOnly": "صورة فقط",
  "createPicturePost": "إنشاء منشور صورة",
  "textWithPictures": "نص مع صور",
  "createPost": "إنشاء منشور",
  "reel": "ريل",
  "total": "المجموع",
  "pay": "الدفع",
  "postSuccessfully": "تم النشر بنجاح",
  "post": "نشر",
  "uploadImage": "تحميل الصورة",
  "fieldIsRequired": "هذا الحقل مطلوب",
  "character": "لا يمكنك كتابة أكثر من 150 حرفًا",
  "typeHer": "اكتب هنا ...",
  "myPosts": "منشوراتي",
  "textPost": "منشور نصي",
  "photoPost": "منشور صورة",
  "photoAndTextPost": "منشور صورة ونص",
  "reelsPost": "منشور بكرات",
  "deleteSuccessfully": "تم الحذف بنجاح",
  "noTextPosts": "لا توجد منشورات نصية في الوقت الحالي.",
  "noPhotoPosts": "لا توجد منشورات صور في الوقت الحالي.",
  "noPosts": "لا توجد منشورات في الوقت الحالي.",
  "noReel": "لا توجد منشورات ريلز في الوقت الحالي.",
  "transferMoney": "تحويل اموال",
  "yourBalance": "رصيدك",
  "yourGift": "هديتك",
  "yourWallet": "محفظتك",
  "hUB": "محفظة 49 HUB",
  "transaction": "للمعاملات الشخصية ",
  "minimum": "الحد الأدنى ",
  "withdraw": "سحب",
  "subscriptions": "الاشتراكات",
  "showMore": "إظهار المزيد",
  "history": "التاريخ",
  "competitions": "المسابقات",
  "requestWithdraw": "طلب سحب",
  "requestTransaction": "طلب للمعاملات الشخصية",
  "years": "سنوات",
  "transfer": "تحويل",
  "save": "حفظ",
  "suscessfullySaved": "تم حفظ البيانات بنجاح",
  "anonymous": "مجهول",
  "viewContact": "عرض جهة الاتصال",
  "mediaLinksAndDocs": "وسائط وروابط ومستندات",
  "search": "بحث",
  "muteNotifications": "كتم الإشعارات",
  "wallpaper": "خلفية الشاشة",
  "disappearingMessages": "الرسائل ذاتية الاختفاء",
  "more": "المزيد",
  "edit": "تعديل",
  "report": "ابلاغ",
  "block": "حظر",
  "clearChat": "مسح الدردشة",
  "exportChat": "نقل الدردشة",
  "addShortcut": "اضافة اختصار",
  "encryption": "التشفير",
  "chatEncryptionMessage": "الرسائل و المكالمات مشفرة تماما بين الطرفين. انقر للتحقق",
  "chatLock": "قفل الدردشة",
  "chatLockMessage": "تمكن من قفل هذة الدردشة و اخفاءها علي هذا الجهاز",
  "createGroupWith": "انشاء مجموعة مع",
  "createGroup": "مجموعة مشتركة",
  "attachments ": "المرفقات",
  "docs": "ملفات",
  "links": "روابط",
  "media": "وسائط",
  "january": "يناير",
  "february": "فبراير",
  "march": "مارس",
  "april": "أبريل",
  "may": "مايو",
  "june": "يونيو",
  "july": "يوليو",
  "august": "أغسطس",
  "september": "سبتمبر",
  "october": "أكتوبر",
  "november": "نوفمبر",
  "december": "ديسمبر",
  "social": "تواصل",
  "services": "الخدمات",
  "socialCalls": "الاتصال والفيديو (الاجتماعي)",
  "servicesCalls": "الاتصال والفيديو(الخدمات)",
  "greet": "تحية",
  "groups": "مجموعات",
  "archive": "أرشيف",
  "lockChat": "قفل الدردشة",
  "unread": "غير مقروءة",
  "broadcast": "اذاعة",
  "newGroup": "مجموعة جديدة",
  "newBroadcast": "رسالة جماعية جديدة",
  "linkedDevice": "الاجهزة المرتبطة",
  "starredMessages": "الرسائل المميزة بنجمة",
  "profile": "الملف الشخصي",
  "about": "الاخبار",
  "phone": "الهاتف",
  "name": "الاسم",
  "nameMessage": "هذا ليس اسم المستخدم أو الرقم السري الخاص بك. سيكون هذا الاسم مرئيًا لجهات اتصال FortyNine الخاصة بك.",
  "selectContact": "حدد جهات الاتصال للمشاركة",
  "addChatShortcut": "اضافة اختصار للدردشة",
  "markAsUnread": "تمييز كغير مقروء",
  "selectAll": "تحديد الكل",
  "selected": "تم تحديده",
  "noData": "لا يوجد بيانات",
  "notSubscription": "لست مشترك",
  "regular": "عادي",
  "areYouSure": "هل أنت متأكد؟",
  "sureUnsubscribe": "هل أنت متأكد من رغبتك في إلغاء الاشتراك؟",
  "renewal": "تجديد",
  "showLess": "إظهار أقل",
  "noHistoryAvailable": "لا يوجد سجل متاح",
  "addSubcategoryToSubscribe": "إضافة فئة فرعية للاشتراك",
  "selectCategory": "تحديد الفئة",
  "noCategoriesAvailable": "لا توجد فئات متاح",
  "selectSubCategory": "تحديد الفئة الفرعية",
  "daily": "يوميًا",
  "weekly": "أسبوعيًا",
  "monthly": "شهريًا",
  "yearly": "سنويًا",
  "noSubscriptionPlans": "لا توجد خطط اشتراك متاحة",
  "premiumPackage": "تمنحك الباقة المميزة الفرصة للظهور بشكل أكبر والحصول على المزيد من النقود المستردة.",
  "requestWithdrawal": "تم إرسال طلب السحب الخاص بك بنجاح في انتظار موافقة الإدارة",
  "complete": "تم إكماله",
  "yearsLast": "سنوات مضت",
  "aBirdInHand": "عصفور في اليد خير من عشرة على الشجرة",
  "permissionDenied": "تم رفض الصلاحيات",
  "contacts": "جهات الاتصال",
  "pleaseLoginRegisterToEnjoyTheApp": "من فضلك قم بتسجيل الدخول او التسجيل للتفاعل معنا",
  "noChatsUntilNow": "لا توجد محادثات حتى الآن",
  "tinder": {
    "header": "تيندر",
    "favorites": "المفضلة",
    "noData": "لا توجد بيانات متاحة",
    "find": "اكتشف"
  },
  "chat_alert_dialog": {
    "pick_chat_type": "اختر نوع الدردشة:",
    "anonymous": "مجهول",
    "regular": "عادي",
    "error": {
      "starting_anonymous": "حدث خطأ أثناء بدء الدردشة المجهولة: {error}",
      "starting_normal": "حدث خطأ أثناء بدء الدردشة العادية: {error}",
      "chat_id_empty": "معرف الدردشة فارغ."
    }
  },
  "user_info": {
    "date_of_birth": "تاريخ الميلاد",
    "gender": "الجنس",
    "followers": "المتابعين",
    "following": "المتابَعون",
    "friends": "الأصدقاء"
  },
  "unarchive": "إلغاء الأرشفة",
  "checkRequest": "يرجى الانتظار للتحقق من الطلب",
  "whatDoYouThink": "بم تفكر؟",
  "peopleYouMayKnow": "أشخاص قد تعرفهم",
  "noFriendsSuggested": "لا يوجد اصدقاء مقترحين",
  "messageSentSuccessfully": "تم إرسال الرسالة بنجاح",
  "days": "يوم",
  "comments": "تعليقات",
  "comment": "تعليق",
  "like": "أعجبني",
  "sad": "أحزنني",
  "angry": "أغضبني",
  "haha": "أضحكني",
  "love": "أحببته",
  "feeling": "يشعر",
  "enterGreetMessage": "أكتب رسالة ترحيب",
  "sendGreetMessage": "أرسل رسالة ترحيب",
  "greetMessage": "رسالة ترحيب",
  "send": "إرسال",
  "addFriend": "إضافة صديق",
  "follow": "متابعة",
  "unFollow": "إلغاء المتابعة",
  "Accept": "قبول",
  "reject": "رفض",
  "remove": "إزالة",
  "postSharedSuccessfully": "تم رفع البوست بنجاج",
  "reportPost": "الابلاغ عن البوست",
  "reportComment": "الابلاغ عن التعليق",
  "reportReply": "الابلاغ عن الرد",
  "youWillReportPost": "سيتم الابلاغ عن هذا البوست",
  "youWillReportComment": "سيتم الابلاغ عن هذا التعليق",
  "youWillReportReply": "سيتم الابلاغ عن هذا الرد",
  "reply": "رد",
  "deletePost": "حذف المنشور",
  "deleteComment": "حذف الكومنت",
  "deleteReply": "حذف الرد",
  "hidePost": "إخفاء المنشور",
  "editComment": "تعديل التعليق",
  "editReply": "تعديل الرد",
  "youWillEditComment": "سوف يتم تعديل تعليقك.",
  "youWillEditReply": "سوف يتم تعديل ردك.",
  "youWillDeletePost": "سيتم حذف منشورك، ولن تتمكن من الحصول عليه مرة أخرى.",
  "youWillDeleteComment": "سيتم حذف تعليقك، ولن تتمكن من الحصول عليه مرة أخرى.",
  "youWillDeleteReply": "سيتم حذف ردك، ولن تتمكن من الحصول عليه مرة أخرى.",
  "youWillHidePost": "سيتم إخفاء منشورك، يمكنك الحصول عليها مرة أخرى.",
  "withKey": "مع",
  "wow": "واو",
  "show": "أظهر",
  "replies": "ردود",
  "typeYourComment": "أكتب تعليقك",
  "typeYourReply": "أكتب ردك",
  "noComments": "لا يوجد تعليقات",
  "noReplied": "لا يوجد ردود",
  "sendMessage": "أرسل رسالة",
  "thisContentIsNotAvailableNow": "هذا المحتوي غير متوفر الان.",
  "withUsers": "مع الأصدقاء",
  "noMedia": "لا يوجد وسائط",
  "discoverPeople": "اكتشف الاصدقاء",
  "unBlock": "إلغاء الحظر",
  "blockedSuccessfully": "تم حظر المستخدم بنجاح.",
  "unBlockedSuccessfully": "تم إلغاء الحظر بنجاح",
  "editProfile": "تعديل الملف الشخصي",
  "posts": "منشورات",
  "Tweets": "تغريدات",
  "savedReels": "ريلز محفوظة",
  "youHaveBlockedThisUser": "لقد حظرت هذا المستخدم.",
  "deleteFriend": "إزالة الصداقة",
  "acceptRequest": "قبول الطلب",
  "removeRequest": "رفض الطلب",
  "normal": "عادي",
  "follower": "متابع",
  "following": "يتابع",
  "livesIn": "يقيم في",
  "reportSentSuccess": "تم ارسال الابلاغ",
  "work": "يعمل",
  "noReels": "لا يوجد مقاطع فيديو",
  "noTweets": "لا يوجد تغريدات",
  "documentation": "توثيق",
  "userName": "اسم المستخدم",
  "typeYourName": "أدخل اسمك",
  "personalPhoto": "الصورة الشخصية",
  "id": "الهوية",
  "front": "الوجه",
  "back": "الخلف",
  "requestVerification": "طلب التحقق",
  "documentSuccessfully": "لقد قمت بتحميل المستند الخاص بك بنجاح. وهو الآن في انتظار مراجعة الإدارة وموافقتها.",
  "noReportCategoriesAvailable": "لا توجد فئات تقرير متاحة",
  "typeReportReason": "اكتب سبب الابلاغ",
  "pleaseSelectReason": "برجاء اختار السبب!",
  "reportSentSuccessfully": "تم ارسال الابلاغ بنجاح",
  "play": "ابدء",
  "showComments": "عرض التعليقات",
  "suggestedForYou": "مقترح لك",
  "hours": "س",
  "minute": "د",
  "confirmNewPassword": "تأكيد كلمة المرور الجديدة",
  "newPassword": "كلمة مرور جديدة",
  "createNewPassword": "إنشاء كلمة مرور جديدة",
  "passwordChangedSuccessfully": "تم تغيير كلمة المرور بنجاح",
  "country": "الدولة",
  "birthDate": "تاريخ الميلاد",
  "socialStatus": "الحالة الاجتماعية",
  "job": "الوظيفة",
  "language": "اللغة",
  "receiveMessages": "استقبال الرسائل",
  "lastSeen": "آخر ظهور",
  "friendsList": "قائمة الأصدقاء",
  "followerList": "قائمة المتابعين",
  "friendRequest": "طلب الصداقة",
  "followRequest": "طلب المتابعة",
  "public": "عام",
  "followers": "المتابعون",
  "onlyMe": "أنا فقط",
  "on": "تشغيل",
  "off": "إيقاف",
  "activity": "نشاط",
  "google": "جوجل",
  "facebook": "فيسبوك",
  "carTrips": "رحلات سيارات",
  "userTrips": "رحلات أفراد",
  "userOwnCarsShareWithThem": "عملاء يملكون سيارات / يمكنك مشاركة الرحلات معهم",
  "noTripsAvailable": "لا يوجد رحلات متوفرة",
  "tripjoinPremuimSubscription": "اشتراك مميز بمشاركة الرحلات",
  "chatSubscription": "أشتراك مميز بخدمة الرسائل",
  "premuimRequest": "طلب مميز",
  "regularRequest": "طلب",
  "subscribeToContactClient": "أشترك للتواصل مع العميل",
  "sendRequest": "ارسل الطلب",
  "enterPhoneNumber": "من فضلك ادخل رقم الهاتف",
  "enterValidPhoneNumber": "من فضلك ادخل رقم هاتف صحيح",
  "welcomeToTripjoin": "مرحبا بك في مشاركة الرحلات",
  "ownCar": "انت تملك سيارة\nشحص سيشارك الرحلة معك ويدفع نصف الثمن",
  "startingPoint": "البداية",
  "destinationPoint": "الوجهة",
  "KM": "كم",
  "repeat": "متكرر",
  "totalPrice": "السعر الإجمالي",
  "brand": "ماركة",
  "model": "  طراز",
  "publish": "نشر",
  "youCantLeaveFieldEmpty": "لا يمكن ترك هذا الجقل فارغا",
  "addressMustBeAtLeast10Chars": "العنوان يجب ان يكون علي الأقل 10 أحرف",
  "searchFind": "ابحث",
  "markAllNotificationAsSeen": "هل ترغب بجعل جميع الأشعارات مرئية؟",
  "requestLog": "سجل الطلبات",
  "requestsHistory": "تاريخ الطلبات",
  "subscribe": "أشترك",
  "deleteRequest": "حذف",
  "subscribtionWillEndAt": "الاشتراك سوف ينتهي في ",
  "TripJoinRequestHistory": "تاريخ طلبات مشاركة الرحلة",
  "noTripRequests": "لا يوجد طلبات لمشاركة الرحلة",
  "tripJoinNotifications": "أشعارات مشاركة الرحلات",
  "subscribeToContactTheClient": "أشترك للتواصل مع العميل",
  "goToRequestHistory": "الذهاب الي تاريخ الطلبات",
  "orContinueWith": "او استمر باستخدام",
  "postSubmitted": "تم إرسال منشورك بنجاح، انتظر موافقة الإدارة",
  "imageNotSelected": "الصورة غير محددة",
  "randomAppearance": "المظهر العشوائي",
  "messageSuccessfully": "تم ارسال الرسالة بنجاح سوف يتم التواصل معك باقرب وقت.",
  "phoneOptional": "الهاتف (اختياري)",
  "TeamHelp": "فريق 49Hub جاهز للمساعدة",
  "moneySuccessfully": "تم إرسال الامول بنجاح.",
  "paymentAddress": "عنوان الدفع",
  "amount": "المبلغ",
  "error_dialog": {
    "audio_playback_fail": "فشل في تحميل الصوت",
    "title": "خطأ",
    "ok_button": "موافق",
    "camera_init_fail": "فشل في تهيئة الكاميرا.",
    "controller_init_fail": "فشل في تهيئة وحدة تحكم الكاميرا.",
    "start_recording_fail": "فشل في بدء التسجيل.",
    "stop_recording_fail": "فشل في إيقاف التسجيل.",
    "video_process_fail": "فشل في معالجة الفيديو:",
    "upload_fail": "فشل في تحميل الفيديو. حاول مرة أخرى."
  },
  "reel_upload_success": {
    "upload_success": "تم تحميل الفيديو بنجاح!"
  },
  "timer": {
    "recording_stops_in": "التسجيل يتوقف في ",
    "seconds": " ثانية"
  },
  "controls": {
    "switch_camera": "تبديل الكاميرا",
    "upload_reel": "ارفع الفيديو الخاص بك"
  },
  "reel_voices": {
    "my_voice": "صوتي",
    "other_voice": "صوت آخر",
    "mix_voices": "دمج الأصوات"
  },
  "free": "متاح",
  "booked": "محجوز",
  "inProgress": "قيد التقدم",
  "muted": "مكتوم",
  "egp": "جنيه",
  "pleaseUploadVideo": "من فضلك قم باختيار فيديو",
  "pleaseUploadImage": "من فضلك قم باختيار صورة",
  "expired": "منتهي",
  "youDontOwnCar": "أنت لا تمتلك سيارة/شخص ما سيشارك الرحلة معك وادفع نصف السعر.",
  "paymentOption": "نظام الدفع",
  "bookSeat": "حجز مقعد",
  "hoursAgo": "ساعات مضت",
  "daysAgo": "ايام مضت",
  "welcomeToCarPool": "مرحباً بك في مشاركة السيارات",
  "youDontHaveCarMessage": "أنت لا تملك سيارة، ستقوم بإنشاء رحلة وتنتظر لمدة ساعة لإعطاء المستخدمين فرصة لحجز مقعد في نفس السيارة.",
  "createRoute": "إنشاء مسار",
  "womenDriverOnly": "سائقات فقط",
  "newRoute": "مسار جديد",
  "youWillFindFewerOption": "ستجد عددًا أقل من السائقات إذا اخترت هذا الخيار.",
  "pricePerSeat": "سعر المقعد الواحد",
  "book": "حجز",
  "comments_header": "التعليقات",
  "add_comment_hint": "أضف تعليقًا...",
  "write_reply_hint": "اكتب ردًا...",
  "view_replies": "عرض الردود",
  "hide_replies": "إخفاء الردود",
  "failed_send_reply": "فشل في إرسال الرد. حاول مرة أخرى.",
  "reel_audio": "الصوت",
  "check_out_reel": "تحقق من هذا الريل!",
  "reel_saved": "تم حفظ الريل",
  "reel_unsaved": "تم ازالة الريل من المحفوظات",
  "use_audio": "استخدام الصوت",
  "audio_load_fail": "فشل في تحميل الصوت!",
  "no_reels": "لا توجد ريلز",
  "one_reel": "1 ريل",
  "multiple_reels": "ريلز",
  "gift_body": {
    "no_name": "بدون اسم",
    "gift_sent": "تم إرسال الهدية",
    "sent_successfully": "تم الإرسال بنجاح!",
    "amount_deducted": "المبلغ المخصوم",
    "insufficient_funds": "الأموال غير كافية",
    "insufficient_funds_message": "ليس لديك أموال كافية في محفظتك.",
    "error": "خطأ",
    "unexpected_error": "خطأ غير متوقع!",
    "ok": "موافق",
    "charge_wallet": "شحن المحفظة",
    "send_a_gift": "أرسل هدية",
    "recharge": "شحن"
  },
  "report_nudity": "يحتوي هذا المحتوى على عري صريح وهو غير مناسب للجماهير العامة.",
  "report_frequent": "النشر المفرط لنفس الرسالة يعطل تجربة المستخدم.",
  "report_fake": "يبرز هذا التقرير انتشار الأخبار الزائفة أو المعلومات المضللة.",
  "report_abuse": "المحتوى المبلغ عنه يتضمن لغة أو سلوكاً مسيئاً.",
  "report_hated": "يتعلق هذا التقرير بمحتوى يروج لخطاب الكراهية أو التمييز.",
  "report_illegal": "المحتوى المبلغ عنه مشتبه في ترويجه لأنشطة غير قانونية.",
  "report_politics": "يتضمن المحتوى المعني دعاية سياسية أو معلومات متحيزة.",
  "report_category_nudity": "عري",
  "report_category_frequent": "متكرر",
  "report_category_fake": "مزيف",
  "report_category_abuse": "إساءة",
  "report_category_hated": "كراهية",
  "report_category_illegal": "غير قانوني",
  "report_category_politics": "سياسة",
  "spotlight_title": "الأضواء",
  "friends_title": "الأصدقاء",
  "following_title": "متابعة",
  "discover_title": "اكتشف",
  "spotlight_follow": "متابعة +",
  "spotlight_following": "متابع",
  "add_story": "أضف قصة",
  "bio": "السيرة الذاتية",
  "friendsAndFollowers": "الأصدقاء و المتابعين",
  "maritalStatus": "الحالة الاجتماعية",
  "single": "أعذب",
  "married": "متزوج",
  "divorced": "مُطلّق",
  "widowed": "أرمل",
  "maleUser": "ذكر",
  "femaleUser": "أنثي",
  "requests": "طلبات الصداقة",
  "blocked": "قائمة الحظر",
  "searchWithName": "ابحث بالاسم...",
  "acceptRequestSuccessfully": "تم قبول طلب الصداقة بنجاح.",
  "removeRequestSuccessfully": "تم إلغاء طلب الصداقة بنجاح.",
  "unFollowSuccessfully": "تم إلغاء المتابعة بنجاح.",
  "tagPeople": "إشارة إلي الأشخاص",
  "selectFeeling": "حدد شعورك",
  "selectActivity": "حدد النشاط",
  "user": "مستخدم عادي",
  "provider": "مقدم خدمة",
  "createAd": "إضافة إعلان",
  "title": "العنوان",
  "adTitle": "عنوان الاعلان",
  "desc": "الوصف",
  "details": "التفاصيل",
  "addImages": "إضافة صور",
  "addImagesDesc": "الحد الأقصى لحجم الملف 5 ميجابايت مقبول بالتنسيقات التالية: jpg، Jpeg، png، gif",
  "write_story": "اكتب قصتك...",
  "add_description": "أضف وصفًا...",
  "text": "نص",
  "picture": "صورة",
  "create_story": "إنشاء قصة",
  "my_contacts": "جهات الاتصال الخاصة بي",
  "my_contacts_except": "جهات الاتصال الخاصة بي باستثناء...",
  "only_share_with": "مشاركة فقط مع...",
  "status_privacy": "خصوصية الحالة",
  "who_can_see_status": "من يمكنه رؤية تحديثات الحالة الخاصة بي",
  "one_contact": "جهة اتصال واحدة",
  "no_contacts_available": "لا توجد جهات اتصال متاحة",
  "privacy_settings_info": "سيؤثر تغيير إعدادات الخصوصية الخاصة بك على جميع حالاتك.",
  "privacy_settings_help": "مساعدة في إعدادات الخصوصية",
  "choose_who_can_see_status": "اختر من يمكنه رؤية تحديثات حالتك:",
  "my_contacts_info": "• جهات الاتصال الخاصة بي: يمكن لجميع جهات الاتصال رؤية حالتك.",
  "my_contacts_except_info": "• جهات الاتصال الخاصة بي باستثناء...: حدد جهات الاتصال التي لا تريد أن ترى حالتك.",
  "only_share_with_info": "• مشاركة فقط مع...: اختر جهات الاتصال التي تريد مشاركة حالتك معها.",
  "noAds": "لا توجد إعلانات في الوقت الحالي.",
  "currency": "جنيه مصري",
  "friend": "صديق",
  "view": "مشاهدة",
  "playedSpins": "عذرا، لقد لعبت كل دوراتك لهذا اليوم.",
  "noFavouriteCategory": "لا يوجد فئة مفضلة في الوقت الحالي.",
  "noFavouriteSubCategory": "لا توجد فئة فرعية مفضلة في الوقت الحالي.",
  "face": "فيسبوك 49",
  "insta": "إنستا 49",
  "socialPage": "صفحة اجتماعية",
  "errorLoadingSocialPage": "خطأ في تحميل الصفحة الاجتماعية",
  "updateSuccessfully": "تم التحديث بنجاح",
  "carpool": "مشاركة السيارة",
  "yourRequestHasBeenSentYouWillReceiveOffersShortly": "تم إرسال طلبك. ستتلقى العروض قريبًا.",
  "thisFieldIsRequiredWithPeriod": "هذا الحقل مطلوب.",
  "pickupLocation": "موقع الاستلام",
  "destination": "الوجهة",
  "pickupTime": "وقت الاستلام",
  "cargoDescription": "وصف الحمولة",
  "applicationDoesNotDeductPercentageFromServiceProvider": "التطبيق لا يخصم أي نسبة من مقدم الخدمة.",
  "premiumPackageGivesOpportunityToBeMoreVisible": "الباقة المميزة تمنحك فرصة الظهور بشكل أكبر والحصول على استرداد نقدي أكبر.",
  "freeCancellation": "إلغاء مجاني",
  "request": "طلب",
  "driverDashboard": "لوحة القيادة للسائق",
  "newBookingsAreWaitingYou": "الحجوزات الجديدة تنتظرك، اذهب إلى لوحة القيادة للسائق واستكشف المزيد!",
  "Call": "اتصال",
  "Message": "رسالة",
  "Report": "تقرير",
  "receiveFawry": "طلب بطاقة الصفراء الخاص بك ناجح! تم خصم 50. ستتلقى إشعارًا عندما تكون بطاقتك جاهزة للاستلام في أي فرع من فوري.",
  "doYellowCard": "هل لديك بطاقة صفراء؟",
  "yellowCardNumber": "رقم هاتف البطاقة الصفراء",
  "atLeast300YellowCard": "تحتاج إلى 300 على الأقل لطلب بطاقة صفراء.",
  "WillBeDeducted": "طلب بطاقة صفراء (سيتم خصم 50)",
  "iDFrontAndBack": "قم بتحميل هويتك (الوجه والظهر):",
  "uploadFrontID": "تحميل الهوية الأمامية",
  "frontIDUploaded": "تم تحميل الهوية الأمامية",
  "uploadBackID": "تحميل الهوية الخلفية",
  "BackIDUploaded": "تم تحميل الهوية الخلفية",
  "pleaseEnterFrontIdAndBackId": "يرجى إدخال الهوية الأمامية والخلفية للاستمرار في طلب البطاقة الصفراء",
  "submitYellowCardRequest": "إرسال طلب البطاقة الصفراء",
  "Other": "اخري",
  "pleaseEnterYourPhoneNumber": "الرجاء إدخال رقم هاتفك",
  "invalidPhoneNumber": "رقم هاتف غير صالح",
  "successfullyReceiveYourMoneyShortly": "لقد قمت بتقديم الدفع بنجاح، تحقق من رصيدك، ستتلقى أموالك قريبًا",
  "chooseInstaPayOption": "اختر خيار InstaPay",
  "instaPayAccount": "حساب InstaPay",
  "instaPayUsernameOrShortcut": "اسم مستخدم InstaPay أو اختصار",
  "bankAccount": "حساب بنكي",
  "cardNumber": "رقم البطاقة",
  "type": "النوع:",
  "account": "الحساب",
  "bankAccountNumber": "رقم الحساب البنكي",
  "pleaseEnterBankAccountNumber": "يرجى إدخال رقم الحساب البنكي",
  "pleaseEnter1016digits": "يرجى إدخال رقم حساب بنكي صحيح (10-16 أرقام)",
  "bankName": "اسم البنك",
  "pleaseEnterBankName": "يرجى إدخال اسم البنك",
  "bankNameCanOnlyContainLetters": "اسم البنك يمكن أن يحتوي فقط على حروف",
  "pleaseEnterCardNumber": "يرجى إدخال رقم البطاقة",
  "enterNumber16digits": "يرجى إدخال رقم بطاقة صحيح (16 رقم)",
  "invalidCardNumber": "رقم البطاقة غير صالح",
  "pleaseEnterUsername": "يرجى إدخال اسم المستخدم",
  "usernameContainLettersNumbersUnderscores": "اسم المستخدم يمكن أن يحتوي فقط على حروف، أرقام، وتسطير سفلي",
  "paymentOptions": "خيارات الدفع",
  "enterYourCreditCardDetails": "أدخل تفاصيل بطاقة الائتمان الخاصة بك",
  "enterPaymobLink": "أدخل رابط Paymob الخاص بك",
  "enterBankAccountDetails": "أدخل تفاصيل حسابك البنكي",
  "youCanEnjoyServingYourClientsUsingYourCarByClickingTheRegisterButtonAbove": "يمكنك الاستمتاع بخدمة عملائك باستخدام سيارتك عن طريق النقر على زر التسجيل أعلاه.",
  "theTripHasBeenSuccessfullyClosed": "تم إغلاق الرحلة بنجاح.",
  "yourRequest": "طلبك",
  "yourRequestHasBeenSentYoullReceiveOffersShortly": "تم إرسال طلبك. ستتلقى العروض قريبًا.",
  "theRequestHasBeenSuccessfullyApproved": "تمت الموافقة على الطلب بنجاح.",
  "theRequestWasSuccessfullyRejected": "تم رفض الطلب بنجاح.",
  "tripIsCompleted": "تمت الرحلة",
  "newOffer": "عرض جديد",
  "carModel": "طراز السيارة",
  "orders": "الطلبات",
  "completeTrip": "إكمال الرحلة",
  "decline": "رفض",
  "subscribeToContactToTheDriver": "اشترك للتواصل مع السائق",
  "youHaveToSelectOneSubCategory": "يجب عليك اختيار فئة فرعية واحدة!",
  "chooseYourFavoriteSubCategory": "اختر الفئة الفرعية المفضلة لديك!",
  "youHaveToFillYourReceiptPoint": "يجب عليك ملء نقطة الاستلام!",
  "youHaveToFillYourDeliveryPoint": "يجب عليك ملء نقطة التسليم!",
  "youHaveToFillYourTime": "يجب عليك ملء الوقت!",
  "youHaveToFillYourDate": "يجب عليك ملء التاريخ!",
  "pickupDate": "تاريخ الاستلام",
  "youHaveToFillYourDescription": "يجب عليك ملء الوصف!",
  "youHaveToFillYourOfferPrice": "يجب عليك ملء سعر العرض!",
  "youHaveToFillYourPhone": "يجب عليك ملء رقم الهاتف!",
  "pickupDashboard": "لوحة تحكم الاستلام",
  "trips": "الرحلات",
  "information": "معلومات",
  "subscribeToSendOfferContactTheClient": "اشترك لإرسال عرض / التواصل مع العميل",
  "registrationForm": "نموذج التسجيل",
  "deadlineSubscription": "اشتراك الموعد النهائي",
  "subcategoryName": "اسم الفئة الفرعية",
  "addSubscription": "إضافة اشتراك",
  "deadlineId": "هوية الموعد النهائي",
  "deadlineLicense": "ترخيص الموعد النهائي",
  "deadlineDriverLicense": "رخصة القيادة الموعد النهائي",
  "yourTrips": "رحلاتك",
  "profit": "الربح",
  "clientsRating": "تقييم العملاء",
  "deleteRegistration": "حذف التسجيل",
  "successUpdateDriver": "تم تحديث السائق بنجاح",
  "welcomeToShipRegister": "مرحبًا بك في سجل الشحن",
  "subCategory": "فئة فرعية",
  "carPicture": "صورة السيارة",
  "idNumber": "رقم الهوية",
  "plateInformation": "معلومات اللوحة",
  "drivingLicenseExpiryDate": "تاريخ انتهاء رخصة القيادة",
  "licenseExpiryDate": "تاريخ انتهاء الترخيص",
  "update": "تحديث",
  "completed": "مكتمل",
  "trip": "رحلة",
  "firstNameIsRequired": "الاسم الأول مطلوب!",
  "lastNameIsRequired": "الاسم الأخير مطلوب!",
  "phoneIsRequired": "رقم الهاتف مطلوب!",
  "thisFieldIsRequired": "هذا الحقل مطلوب!",
  "thisFieldIsRequired2": "هذا الحقل مطلوب.",
  "fillYourIdExpiryDate": "املأ تاريخ انتهاء الهوية!",
  "fillYourDrivingLicenseExpiryDate": "املأ تاريخ انتهاء رخصة القيادة!",
  "fillYourLicenseExpiryDate": "املأ تاريخ انتهاء الترخيص!",
  "fillYourCarModel": "املأ طراز السيارة!",
  "rider": "راكب",
  "continueKey": "استمرار",
  "myBookings": "حجوزاتي",
  "runningTrips": "رحلات جارية",
  "expiredTrips": "رحلات منتهية",
  "idExpiryDate": "تاريخ انتهاء الهوية",
  "licenseFrontAndBack": "قم بتحميل الترخيص  (الوجه والظهر)",
  "subscribed": "مشترك",
  "unsubscribed": "غير مشرك",
  "expiredRequests": "طلبات منتهية الصلاحية",
  "filter": "تصفية",
  "beAStar": "كن نجم",
  "pleaseEnterTheAmount": "الرجاء إدخال المبلغ",
  "selectBankName": "حدد اسم البنك",
  "pleaseSelectPaymentMethod": "الرجاء تحديد طريقة الدفع",
  "sureWithdrawMoney": "هل أنت متأكد من سحب الأموال؟",
  "requestYellowCard": "طلب البطاقة الصفراء",
  "deducted": "سيتم خصم المبلغ",
  "fullName": "الاسم الكامل",
  "pleaseEnterFullName": "الرجاء إدخال الاسم الكامل",
  "nationalIdNumber": "رقم الهوية الوطنية",
  "pleaseEnterNationalId": "الرجاء إدخال رقم الهوية الوطنية",
  "pleaseEnter14Digit": "الرجاء إدخال 14 رقمًا",
  "yellowCardSuccess": "لقد قمت بنجاح بإرسال الدفعة للتحقق من رصيد البطاقة الصفراء الخاصة بك.",
  "walletDigital": "لقد قمت بإرسال الدفعة بنجاح. تحقق من صندوق الوارد الخاص بك، وسوف تتلقى أموالك قريبًا.",
  "notWalletDigital": "لقد قمت بإرسال الدفعة بنجاح. تحقق من صندوق الوارد الخاص بك، وسوف تتلقى قسيمة تتضمن أموالك قريبًا.",
  "HaveWallet": "هل لديك محفظة؟",
  "submitPayment": "إرسال الدفعة",
  "cashOutOption": "خيار السحب النقدي",
  "SubscriberCompletionRate": "معدل إكمال المشتركين",
  "ChanceDetails": "تفاصيل الفرصة",
  "ProductDescription": "وصف المنتج",
  "Typethevalueyouwanttoparticipation": "اكتب القيمة التي تريد المشاركة بها",
  "CreateChance ": "إنشاء فرصه",
  "enterPrice": "ادخل السعر",
  "enterTitle": "ادخل العنوان",
  "enterDescription": "ادخل وصف",
  "payAtLeast1": "ادفع 1 جنيه مصري على الأقل ونشر منتج أحلامك الذي تريد شراءه!!!",
  "oneUserWillR": "سيفوز مستخدم واحد بشكل عشوائي في كل شهر",
  "moreSubscriptionMore": "كلما زاد الاشتراك زادت الفرصة!",
  "select": "اختيار",
  "uploadOneImage": "قم بتحميل صورة واحدة على الأقل!",
  "editMyAds": "تعديل الاعلان",
  "requestTripJoin": "طلب الانضمام إلى الرحلة",
  "requestAd": "طلب إعلان",
  "breakfast": "الإفطار",
  "items_count": "العناصر",
  "noName": "لا يوجد اسم",
  "unknownRestaurant": "مطعم غير معروف",
  "noOrders": "لا توجد طلبات",
  "noDate": "لا يوجد تاريخ",
  "noSubscription": "لا توجد اشتراك",
  "unknownFood": "طعام غير معروف",
  "restaurantMenu": "قائمة المطعم",
  "view_cart": "عرض السلة",
  "your_cart_empty": "سلتك فارغة",
  "your_cart": "سلتك",
  "restaurant_total": "إجمالي المطعم:",
  "premium_request": "طلب مميز",
  "your_phone_number": "رقم هاتفك",
  "please_enter_phone_number": "يرجى إدخال رقم هاتفك",
  "submit_order": "إرسال الطلب",
  "removeFavouriteSuccessfully": "إزالة الإعلان المفضل بنجاح",
  "selectValidUser": "لم يتم العثور على المستخدم أو أنه غير صالح، يرجى تحديد مستخدم صالح",
  "notEnoughMoneyWallet": "لا يوجد ما يكفي من المال في المحفظة",
  "transactionSuccessful": "تمت المعاملة بنجاح",
  "yourTransactionWasSuccessful": "كانت معاملتك ناجحة",
  "transferAmount": "مبلغ التحويل",
  "premiumPackageMoreVisibilityCashback": "تمنحك الباقة المميزة الفرصة لتكون أكثر وضوحًا وتحصل على المزيد من الاسترداد النقدي.",
  "inFront": "من الامام",
  "behind": "من الخلف",
  "drivingLicense": "رخصة القيادة",
  "theApplicationDoesNotDeductAnyPercentage": "لا يقوم التطبيق بخصم أي نسبة من مقدم الخدمة.",
  "youWillGetPoundsAnnually": "سوف تحصل على 3,650 جنيهًا إسترلينيًا سنويًا إذا قمت بالاشتراك.",
  "license": "رخصة",
  "snapCopyOfBillPayment": "التقط نسخة من دفع الفاتورة",
  "paymentSuccessful": "تم الدفع بنجاح",
  "sendReviewApproval": "إرسال للمراجعة والموافقة",
  "youWin": "لقد فزت!",
  "shipping": "شحن",
  "food": "اكله",
  "thereNoItems": "لا يوجد أي عناصر",
  "areDeleteThisAd": "هل أنت متأكد من أنك تريد حذف هذا الإعلان!",
  "offers": "العروض",
  "contactPhone": "رقم الهاتف للاتصال",
  "booking": "الحجز",
  "insufficientAmount": "الرصيد غير كافٍ",
  "selectAmountToCharge": "اختر مبلغًا للشحن",
  "chargeNow": "اشحن الان",
  "premiumSubscription": "الاشتراك المميز",
  "regularSubscription": "الاشتراك العادي",
  "notSubscribed": "غير مشترك",
  "seeAll": "عرض الكل",
  "premiumRequest": "طلب مميز",
  "normalRequest": "طلب عادي",
  "adRequests": "طلبات الاعلان",
  "showAdRequests": "عرض طلبات الاعلان",
  "comfort": "مريح",
  "minutesAgo": "من دقيقه",
  "Phonenumbercannotbewrittenindescription": "لا يمكن كتابه رقم هاتف في الوصف",
  "mutualFriend": "صديق مشترك",
  "womenOnly": "للنساء فقط",
  "chance": "فرصة",
  "subTab": "علامة تبويب فرعية",
  "exactly2items": "يرجى اختيار عنصرين بالضبط.",
  "snap": "التقاط",
  "spotlight": "تسليط الضوء",
  "atLeast3atMost5items": "يرجى اختيار ما لا يقل عن 3 وما لا يزيد عن 5 عناصر.",
  "editPage": "تعديل الصفحة",
  "navigateBar": "شريط التنقل",
  "favoriteCategory": "الفئة المفضلة",
  "customPage": "صفحة مخصصة",
  "activatePage": "تفعيل الصفحة",
  "pagePreview": "معاينة الصفحة",
  "service": "خدمة",
  "atLeast3atMost8items": "يرجى اختيار ما لا يقل عن 3 وما لا يزيد عن 8 عناصر.",
  "failedToLoadCategories": "فشل في تحميل الفئات",
  "nOFoundUsers": "لم يتم العثور على مستخدمين",
  "chatWith": "الدردشة مع",
  "Unfollow": "إلغاء المتابعة",
  "stopSeeing": "إيقاف عرض المنشورات مع الاحتفاظ به كصديق",
  "unblock": "إلغاء الحظر",
  "youCanRemove": "يمكنك إزالة",
  "fromBlockedList": "من قائمة المحظورين",
  "unfriend": "إلغاء الصداقة",
  "fromFriendsList": "من قائمة الأصدقاء",
  "shareProfile": "مشاركة الملف الشخصي",
  "createdOn": "تم الإنشاء في",
  "active": "نشط",
  "pending": "قيد الانتظار",
  "adReviewSoon": "يتم مراجعة هذا الإعلان وسيكون متاحًا قريبًا.",
  "sureRemoveAd": "هل أنت متأكد من رغبتك في إزالة الإعلان؟",
  "markSsSold": "تمييز كمباع",
  "deactivate": "تعطيل",
  "tel": "هاتف",
  "chats": "المحادثات",
  "deleteAd": "حذف الإعلان",
  "rent": "إيجار",
  "sale": "بيع",
  "seat": "مقعد",
  "repeated": "مكرر",
  "subscription": "اشتراك",
  "tripJoinAds": "إعلانات الانضمام إلى الرحلة",
  "adSoldout": "هل أنت متأكد من أنك تريد تعيين هذا الإعلان كمباع؟",
  "viewAll": "عرض الكل",
  "addACaption": "أضف وصفًا...",
  "and": "و",
  "otherContacts": "جهات اتصال أخرى",
  "registered": "مسجل",
  "add": "إضافة",
  "noDocs": "لا توجد مستندات",
  "noLinks": "لا توجد روابط",
  "broadcasts": "البث",
  "myBroadcasts": "بثي",
  "channelInfo": "معلومات القناة",
  "file": "ملف",
  "enjoyServingClientsUsingCar": "يمكنك تقديم خدمات لعملائك باستخدام سيارتك عن طريق الضغط على زر التسجيل أعلاه",
  "tripSuccessfullyClosed": "تم إغلاق الرحلة بنجاح",
  "selectDropOffLocation": "اختر موقع التسليم",
  "requestSentOffersComingSoon": "تم إرسال طلبك. ستتلقى العروض قريبًا",
  "requestSuccessfullyApproved": "تمت الموافقة على الطلب بنجاح",
  "requestSuccessfullyRejected": "تم رفض الطلب بنجاح",
  "tripCompleted": "تمت الرحلة",
  "subscribeToContactDriver": "اشترك للتواصل مع السائق",
  "chooseFavoriteSubCategory": "اختر الفئة الفرعية المفضلة!",
  "officePrice": "سعر المكتب",
  "enterYourRoute": "ادخل مسارك",
  "selectPickupLocation": "اختر موقع الانطلاق",
  "shippingDetails": "تفاصيل الشحن",
  "whereToDeliver": "ألى مكان التسليم",
  "toAddress": "ألى العنوان",
  "entrance": "مدخل",
  "whatToDeliver": "ماذا تريد تسليمه",
  "notes": "ملاحظات",
  "offerPrice": "سعر العرض",
  "whereToPickUp": "ألى مكان الانطلاق",
  "fromAddress": "من العنوان",
  "youHaveReportedThisTrip": "لقد تم تقديم تقرير لهذه الرحلة",
  "newRide": "رحلة جديدة",
  "cancelRequest": "إلغاء الطلب",
  "sendOffer": "إرسال العرض",
  "shareTransactionDetails": "مشاركة تفاصيل المعاملة",
  "serveClientsByClickRegister": "خدمة العملاء عن طريق النقر على زر التسجيل."
};
static const Map<String,dynamic> en = {
  "nnew": "New",
  "today": "Today",
  "tommorow": "Tomorrow",
  "meeting": "Meeting",
  "join": "Join",
  "schedule": "Schedule",
  "scheduleAMeeting": "Schedule a Meeting",
  "startDateBeginValidation": "Start Date must be before End Date",
  "startDateTimeValidation": "Start Date must be in the future",
  "pleaseFillAllFields": "Please fill all fields",
  "done": "Done",
  "date": "Date",
  "selectADate": "Select date",
  "from": "From",
  "to": "To",
  "club": "Club Voice",
  "share": "Share",
  "screen": "screen",
  "addAcalender": "Add a calender",
  "meetingId": "Meeting ID:",
  "startNow": "Start Now:",
  "emptyMeetingIdValidator": "Please enter some text:",
  "invalidInputValidator": "Invalid input: Only numbers, /, and . are allowed",
  "meetingMustBe8Characters": "Meeting ID must be 8 numbers",
  "joinMeeting": "Join Meeting",
  "joinMeetingWithShareScreen": "Join a Meeting with Share screen",
  "joinMeetingWithId": "Joining meeting with ID:",
  "addTopic": "Add topic",
  "addLiveGoal": "Add a LIVE goal",
  "startAMeeting": "Start a meeting",
  "faceBeautification": "Face beautification",
  "goLive": "Go LIVE",
  "usePersonalMeetingId": "Use personal meeting ID",
  "videoOn": "Video on",
  "mute": "Mute",
  "unmute": "Unmute",
  "startVideo": "Start Video",
  "stopVideo": "Stop Video",
  "participants": "Participants",
  "whiteBoard": "WhiteBoard",
  "roomCode": "Room Code",
  "copiedSuccessfully": "Copied Successfully",
  "saySomthing": "Say somthing...",
  "end": "End",
  "leave": "Leave",
  "EndMeetingForAll": "End meeting for all",
  "leaveMeeting": "Leave meeting",
  "live": "Live",
  "clubVoice": "Club Voice",
  "roomSubject": "Room Subject",
  "pleaseEnterSimpleSubject": "Please enter a simple description",
  "enterRoomSubject": "Enter room subject",
  "roomSubjectValidation": "Room subject cannot be empty",
  "createRoom": "Create Room",
  "audience": "Audience",
  "voiceChanging": "Voice Changing",
  "audioEffects": "Audio Effects",
  "reverb": "Reverb",
  "meetingTitle": "Meeting Title",
  "noRooms": "No Rooms",
  "editYourLiveGoal": "Edit your LIVE goal",
  "goalExpirationIn4Hours": "The LIVE goal will expire in 4 hours",
  "describeYourGoal": "Describe Your Goal",
  "progress": "Progress:",
  "gifts": "Gifts:",
  "goalsAreSelectedSuccess": "Goals are selected successfully",
  "selectATopic": "Choose Topic for LIVE",
  "arabic": "Arabic",
  "english": "English",
  "meal": "Meal",
  "darkMode": "Dark mode",
  "lightMode": "Light mode",
  "voice": "Voice",
  "restaurantName": "ٌRestaurant Name",
  "theCommercialRegister": "The Commercial Register",
  "theApplicationDoesNotDeductAnyPercentageFromTheServiceProvider": "The application does not deduct any percentage from the service provider.",
  "youWillGetEGP3650PerYearIfYouSubscribeDaily": "You will get 3650 EGP per year if you subscribe daily.",
  "welcomeToResturantRegisteration": "Welcome to Resturant Registeration",
  "selecteSubcategory": "Selecte Subcategory:",
  "photoForRestaurant": "Photos For Restaurant",
  "searchForFavouriteMeals": "Search For Favourite Meals",
  "firstPage": "First Page",
  "secondPage": "Second Page",
  "thirdPage": "Third Page",
  "selectGovernorate": "Select Governorate",
  "selectCity": "Select City",
  "newBookingsAreWaitingYouGoToResturantDashboardAndExploreMore": "New bookings are waiting. Go to Riders dashboard and explore more.",
  "premium": "Premium",
  "restaurantDashboard": "Restaurant Dashboard",
  "allRestaurants": "All Restaurants",
  "restaurantsForSelectedMeal": "Restaurants For Selected Meal",
  "itemName": "Item Name",
  "comma": ",",
  "noResultFound": "No Result Found",
  "youCanEnjoyServingYourClintsUsingYourRestaurantByClickingOnTheRigesterButtonAbove": "You can enjoy serving your clints using your Rdiers by clicking on the rigester button above.",
  "selectSubcategoryFirst": "Select Subcategory First",
  "UploadingImage": "Uploading Image...",
  "cantLoadCities": "Can't Load Cities",
  "cantLoadGovernorates": "Can't Load Governorates",
  "cantLoadSubCategories": "Can't Load SubCategories",
  "cantLoadRestaurants": "Can't Load Restaurants",
  "cantLoadMainCategories": "Can't Load MainCategories",
  "cantLoadCategories": "Can't Load Categories",
  "cantLoadSpecialities": "Can't Load Specialities",
  "cantLoadSubSubCategories": "Can't Load SubSubCategories",
  "creatingRestaurant": "Creating Restaurant...",
  "price": "Price",
  "salary": "Salary",
  "youHaveSubmittedYourRegistrationSuccessfullyWaitingForAdministrationApproval": "You have submitted your registration successfully, waiting for administration approval",
  "photoForMeal": "Meal",
  "menu": "Menu",
  "submit": "Submit",
  "needToLogin": "Need To Login",
  "completeAllFields": "Complete All Fields",
  "meet": "Meet",
  "cast": "Cast",
  "tweet": "Tweet",
  "reels": "Reels",
  "chat": "Chat",
  "somethingWentWrong": "Something went wrong",
  "find": "Find",
  "health": "Health",
  "ship": "Ship",
  "ride": "Ride",
  "lang": "ع",
  "ads": "Ads",
  "ad": "Ad",
  "wallet": "Wallet",
  "gift": "Gift",
  "balance": "Balance",
  "pickMe": "Pick Me",
  "tripJoin": "Trip Join",
  "auction": "Auction",
  "installments": "Installments",
  "craft": "Craft",
  "homeService": "Home Service",
  "homeEssentials": "Home Essentials",
  "scenery": "Scenery",
  "specialities": "Specialities",
  "medicalService": "Medical Service",
  "doctor": "Doctor",
  "doctors": "Doctors",
  "call": "Call",
  "clinicVisit": "Clinic Visit",
  "emergency": "Emergency",
  "homeVisit": "Home Visit",
  "firstName": "First Name",
  "phoneNumber": "Phone Number",
  "speciality": "Speciality",
  "address": "Address",
  "confirm": "Confirm",
  "doctorList": "Doctor List",
  "noDoctorsFound": "No doctors found",
  "governorate": "Governorate",
  "city": "City",
  "emptyFieldNotValid": "Empty Field Not Valid",
  "login": "Login",
  "register": "Register",
  "emailOrPhone": "Email Or Phone",
  "password": "Password",
  "forgetPassword": "Forget Password?",
  "lastName": "Last Name",
  "gender": "Gender",
  "code": "Referral Code(Optional)",
  "female": "Female",
  "male": "Male",
  "conditions": "Terms,Rules & Conditions",
  "iAcceptAll": "I Accept All",
  "Accept": "Accept",
  "reject": "Reject",
  "terms": "Please accept the terms and conditions to continue.",
  "message": "Message",
  "photo": "Photo",
  "video": "Video",
  "advertiseYourCompany": "Advertise Your Company",
  "quraan": "Quraan",
  "azkar": "Azkar",
  "favouriteCategories": "Favourite Categories",
  "favouriteSubCategories": "Favourite Sub Categories",
  "favouriteAds": "Favourite Ads",
  "requestHistory": "Requests History",
  "lists": "Lists",
  "myAds": "My Ads",
  "settings": "Settings",
  "privacy": "Privacy",
  "policies": "Policies",
  "shareApp": "Share App",
  "contactUs": "Contact Us",
  "logout": "Logout",
  "luckyWheel": "Lucky Wheel",
  "feelLucky": "Do You feel lucky?",
  "restaurants": "Restaurants",
  "meals": "Meals",
  "openAppSettings": "Open App Settings",
  "pleaseAllowPermissions": "Please allow permissions",
  "allowAccessToYourCamera": "Allow access to your camera",
  "allowAccessToYourMicrophone": "Allow access to your microphone",
  "document": "Document",
  "camera": "Camera",
  "microphone": "Microphone",
  "gallery": "Gallery",
  "audio": "Audio",
  "location": "Location",
  "contact": "Contact",
  "pickPhotoOrVideo": "Pick Photo Or Video",
  "noRideSubcategories": "No Ride Subcategories",
  "enableNotifications": "Enable Notifications",
  "changePassword": "Change Password",
  "disableAccount": "Disable Account",
  "deleteAccount": "Delete Account",
  "alert": "Alert!",
  "disable": "Are you sure you want to disable your account?",
  "delete": "Are you sure you want to delete your account?",
  "specialAds": "Special Ads",
  "friends": "Friends",
  "Doctor": "Doctor",
  "loadingDriver": "Loading Driver",
  "Restaurant": "Restaurant",
  "driver": "Driver",
  "sureLogout": "Are you sure you want to logout?",
  "no": "No",
  "welcomeBack": "Welcome Back",
  "oTP": "OTP Sent successfully",
  "required": "Required",
  "emailFormat": "Enter correct email format",
  "email": "E-mail",
  "typeHere": "Type here",
  "sendOTP": "Send OTP",
  "forget": "Forget Password",
  "verify": "Verify",
  "emailOtp": "Email OTP",
  "verification": "Verification",
  "notifications": "Notifications",
  "checkVerification": "Please check your email to see the verification code ",
  "congratulations": "Congratulations",
  "close": "CLOSE",
  "giftApp": "You got a gift of 400 pounds as a welcome gift for registering on the 49 app.",
  "clearAll": "Clear All",
  "clearNotification": "Are you sure you want to clear all notifications?",
  "showNotification": "Are you sure you want to see all notifications?",
  "clearNoti": "Are you sure you want to clear notifications?",
  "ok": "Ok",
  "winners": "Winners",
  "competition": "Competitions",
  "count": "Count: ",
  "max": "Max: ",
  "money": "Money",
  "points": "Points",
  "notEnoughWheel": "Not enough items to spin the wheel",
  "spin": "Spin",
  "companyAdvertise": "Company Advertise",
  "textOnly": "Text only",
  "createTextPost": "Create Text Post",
  "pictureOnly": "Picture only",
  "createPicturePost": "Create Picture Post",
  "textWithPictures": "Text with pictures",
  "createPost": "Create Post",
  "reel": "Reel",
  "total": "Total",
  "pay": "Pay",
  "postSuccessfully": "Post Successfully",
  "post": "Post",
  "uploadImage": "Upload Image",
  "fieldIsRequired": "Field is required",
  "character": "You can't type more than 150 characters",
  "typeHer": "Type Here ... ",
  "myPosts": "My Posts",
  "textPost": "Text Post",
  "photoPost": "Photo Post",
  "photoAndTextPost": "Photo And Text Post",
  "reelsPost": "Reels Post",
  "deleteSuccessfully": "Delete Successfully",
  "noTextPosts": "There are no text posts at the moment.",
  "noPhotoPosts": "There are no photo posts at the moment.",
  "noPosts": "There are no posts at the moment.",
  "noReel": "There are no reel posts at the moment.",
  "transferMoney": "Transfer Money",
  "yourBalance": "Your Balance is",
  "yourGift": "Your Gift is",
  "yourWallet": "Your Wallet is",
  "hUB": "49 HUB WALLET",
  "transaction": "for personal transaction",
  "minimum": "Minimum ",
  "withdraw": "Withdraw",
  "subscriptions": "Subscriptions",
  "showMore": "Show More",
  "history": "History",
  "competitions": "Competitions",
  "requestWithdraw": "Request Withdraw",
  "requestTransaction": "request for personal transaction",
  "years": "Years",
  "transfer": "Transfer",
  "cancel": "Cancel",
  "save": "Save",
  "suscessfullySaved": "Successfully Saved",
  "anonymous": "Anonymous",
  "viewContact": "View contact",
  "mediaLinksAndDocs": "Media, links and docs",
  "search": "Search",
  "muteNotifications": "Mute notifications",
  "wallpaper": "Wallpaper",
  "disappearingMessages": "Disappearing messages",
  "more": "More",
  "edit": "Edit",
  "report": "Report",
  "block": "Block",
  "clearChat": "Clear chat",
  "exportChat": "Export chat",
  "addShortcut": "Add shortcut",
  "encryption": "Encryption",
  "chatEncryptionMessage": "Messages and calls are end-to-end encrypted. Tap to verify",
  "chatLock": "Chat Lock",
  "chatLockMessage": "Lock and hide this chat from on this device",
  "createGroupWith": "Create group with",
  "createGroup": "Group in Common",
  "attachments ": "Attachments",
  "docs": "Docs",
  "links": "Links",
  "media": "Media",
  "january": "january",
  "february": "february",
  "march": "march",
  "april": "april",
  "may": "may",
  "june": "june",
  "july": "july",
  "august": "august",
  "september": "september",
  "october": "october",
  "november": "november",
  "december": "december",
  "social": "Social",
  "services": "Services",
  "socialCalls": "Call & Video(Social)",
  "servicesCalls": "Call & Video(Services)",
  "greet": "Greet",
  "groups": "Groups",
  "archive": "Archive",
  "lockChat": "Locked Chats",
  "unread": "Unread",
  "broadcast": "Broadcast",
  "newGroup": "New Group",
  "newBroadcast": "New Broadcast",
  "linkedDevice": "Linked Device",
  "starredMessages": "Starred Messages",
  "profile": "Profile",
  "about": "About",
  "phone": "Phone",
  "name": "Name",
  "nameMessage": "This is not your username or pin. This name will be visible to your FortyNine contacts.",
  "selectContact": "Select Contacts to Share",
  "addChatShortcut": "Add chat shortcut",
  "markAsUnread": "Mark as unread",
  "selectAll": "Select all",
  "selected": "Selected",
  "noData": "No Data",
  "notSubscription": "Not Subscription",
  "regular": "Regular",
  "areYouSure": "Are you sure?",
  "sureUnsubscribe": "Are you sure you want to unsubscribe?",
  "renewal": "Renewal",
  "showLess": "Show Less",
  "noHistoryAvailable": "No History Available",
  "addSubcategoryToSubscribe": "Add Subcategory To Subscribe",
  "selectCategory": "Select Category",
  "noCategoriesAvailable": "No categories available",
  "selectSubCategory": "Select SubCategory",
  "daily": "Daily",
  "weekly": "Weekly",
  "monthly": "Monthly",
  "yearly": "Yearly",
  "noSubscriptionPlans": "No subscription plans available",
  "premiumPackage": "The Premium Package gives you the opportunity to be seen more and get more cashback.",
  "requestWithdrawal": "Your request withdrawal sent successfully waiting for administration approval",
  "complete": "Complete",
  "yearsLast": "years last",
  "aBirdInHand": "A bird in the hand is better than two on the tree.",
  "permissionDenied": "Permission denied",
  "contacts": "Contacts",
  "pleaseLoginRegisterToEnjoyTheApp": "Please Login, Register to enjoy the app",
  "noChatsUntilNow": "No Chats until now",
  "confirmNewPassword": "Confirm New Password",
  "newPassword": "New Password",
  "createNewPassword": "Create New Password",
  "passwordChangedSuccessfully": "Password Changed Successfully",
  "country": "Country",
  "birthDate": "Birth Date",
  "socialStatus": "Social Status",
  "job": "Job",
  "language": "Language",
  "receiveMessages": "Receive Messages",
  "lastSeen": "Last Seen",
  "friendsList": "Friends List",
  "followerList": "Followers List",
  "friendRequest": "Friend Request",
  "followRequest": "Follow Request",
  "public": "Public",
  "followers": "Followers",
  "onlyMe": "Only Me",
  "on": "ON",
  "off": "Off",
  "activity": "Activity",
  "unarchive": "Unarchive",
  "availableTrips": "Available Trips",
  "checkRequest": "Please wait to check request",
  "reportSentSuccess": "Report sent successfully",
  "whatDoYouThink": "What do you think about?",
  "peopleYouMayKnow": "People you may know",
  "noFriendsSuggested": "No Friends Suggested",
  "days": "d",
  "comments": "Comments",
  "comment": "Comment",
  "like": "Like",
  "sad": "Sad",
  "angry": "Angry",
  "haha": "Haha",
  "love": "Love",
  "feeling": "Feeling",
  "messageSentSuccessfully": "Message Sent Successfully",
  "enterGreetMessage": "Enter Greet Message",
  "greetMessage": "Greet Message",
  "send": "Send",
  "addFriend": "Add Friend",
  "follow": "Follow",
  "remove": "Remove",
  "sendGreetMessage": "Send Greet Message",
  "postSharedSuccessfully": "Post Shared Successfully",
  "youWillReportPost": "Your Well Reports This Post",
  "youWillReportComment": "Your Well Reports This Comment",
  "youWillReportReply": "Your Well Reports This Reply",
  "youWillDeletePost": "Your post will be deleted, and you cannot get it again.",
  "youWillDeleteComment": "Your comment will be deleted, and you cannot get it again.",
  "youWillDeleteReply": "Your reply will be deleted, and you cannot get it again.",
  "youWillHideReply": "Your Post will be hide, and you can get it again.",
  "reportPost": "Report Post",
  "editComment": "Edit Comment",
  "editReply": "Edit Reply",
  "youWillEditComment": "Your Will Edit Your Comment.",
  "youWillEditReply": "Your Will Edit Your Reply.",
  "reportComment": "Report Comment",
  "reportReply": "Report Reply",
  "reply": "Reply",
  "deletePost": "Delete Post",
  "deleteComment": "Delete Comment",
  "deleteReply": "Delete Reply",
  "withKey": "With",
  "hidePost": "Hide Post",
  "wow": "Wow",
  "show": "Show",
  "replies": "Replies",
  "typeYourComment": "Type Your Comment",
  "typeYourReply": "Type Your Reply",
  "noComments": "No Comments",
  "noReplied": "No Replies",
  "sendMessage": "Send Message",
  "thisContentIsNotAvailableNow": "This content is not available now.",
  "withUsers": "With Users",
  "discoverPeople": "Discover People",
  "unBlock": "Un Block",
  "blockedSuccessfully": "Blocked user successfully.",
  "unBlockedSuccessfully": "Unblocked user successfully.",
  "editProfile": "Edit Profile",
  "Tweets": "Tweets",
  "posts": "Posts",
  "savedReels": "Saved Reels",
  "youHaveBlockedThisUser": "You have blocked this user.",
  "unFollow": "Un Follow",
  "deleteFriend": "Delete Friend",
  "acceptRequest": "Accept Request",
  "removeRequest": "Remove Request",
  "normal": "Normal",
  "follower": "Follower",
  "following": "Following",
  "livesIn": "Lives in",
  "work": "Work",
  "noReels": "No Reels",
  "noTweets": "No Tweets",
  "documentation": "Documentation",
  "userName": "User Name",
  "typeYourName": "Type Your Name",
  "personalPhoto": "Personal Photo",
  "id": "ID",
  "front": "Front",
  "back": "Back",
  "requestVerification": "Request Verification",
  "documentSuccessfully": "You have successfully uploaded your document. It is now awaiting administration review and approval.",
  "noReportCategoriesAvailable": "No report categories available",
  "typeReportReason": "Type report reason",
  "pleaseSelectReason": "Please select a reason!",
  "reportSentSuccessfully": "Report sent successfully",
  "play": "Play",
  "showComments": "Show Comments",
  "suggestedForYou": "Suggested For You",
  "hours": "H",
  "minute": "m",
  "tinder": {
    "header": "Tinder",
    "favorites": "Favorites",
    "noData": "No Data Available",
    "find": "Find"
  },
  "chat_alert_dialog": {
    "pick_chat_type": "Pick a Chat Type:",
    "anonymous": "Anonymous",
    "regular": "Regular",
    "error": {
      "starting_anonymous": "Error starting anonymous chat: {error}",
      "starting_normal": "Error starting normal chat: {error}",
      "chat_id_empty": "Chat ID is empty."
    }
  },
  "user_info": {
    "date_of_birth": "Date of Birth",
    "gender": "Gender",
    "followers": "Followers",
    "following": "Following",
    "friends": "Friends"
  },
  "google": "Google",
  "facebook": "Facebook",
  "carTrips": "Car Trips",
  "userTrips": "User Trips",
  "userOwnCarsShareWithThem": "Users own cars/share the trip with them",
  "noTripsAvailable": "There are no trips available till now",
  "tripjoinPremuimSubscription": "Trip Join Subscription",
  "chatSubscription": "Chat Subscription",
  "premuimRequest": "Premium Request",
  "regularRequest": "Request",
  "subscribeToContactClient": "Subscribe to contact the client!",
  "sendRequest": "Send Request",
  "enterPhoneNumber": "Please enter mobile number",
  "enterValidPhoneNumber": "Please enter valid mobile number",
  "welcomeToTripjoin": "Welcome To Trip Join",
  "ownCar": "You own a car!\nSomeone will share trip with you / pay half price",
  "startingPoint": "Starting Point",
  "destinationPoint": "Destination Point",
  "KM": "KM",
  "repeat": "Repeat",
  "totalPrice": "Total Price",
  "brand": "Brand",
  "model": "Model",
  "publish": "Publish",
  "youCantLeaveFieldEmpty": "You can't leave the field empty",
  "addressMustBeAtLeast10Chars": "Address must be at least 10 characters",
  "searchFind": "Find",
  "markAllNotificationAsSeen": "Do you want to mark all notifications as seen?",
  "requestLog": "Request Log",
  "requestsHistory": "Requests History",
  "subscribe": "Subscribe",
  "deleteRequest": "Delete",
  "subscribtionWillEndAt": "Subscribtion will end at ",
  "TripJoinRequestHistory": "Trip Join Request History",
  "noTripRequests": "There are no requests history",
  "tripJoinNotifications": "Trip Join Notification",
  "subscribeToContactTheClient": "Subscribe to contact the client",
  "goToRequestHistory": "Go to Request History",
  "orContinueWith": "Or Continue with",
  "error_dialog": {
    "audio_playback_fail": "Failed to load audio",
    "title": "Error",
    "ok_button": "OK",
    "camera_init_fail": "Failed to initialize the camera.",
    "controller_init_fail": "Failed to initialize the camera controller.",
    "start_recording_fail": "Failed to start recording.",
    "stop_recording_fail": "Failed to stop recording.",
    "video_process_fail": "Failed to process the video:",
    "upload_fail": "Failed to upload video. Try again."
  },
  "reel_upload_success": {
    "upload_success": "Reel uploaded successfully!"
  },
  "timer": {
    "recording_stops_in": "Recording stops in ",
    "seconds": " seconds"
  },
  "controls": {
    "switch_camera": "Switch Camera",
    "upload_reel": "Upload your Reel"
  },
  "reel_voices": {
    "my_voice": "My Voice",
    "other_voice": "Other Voice",
    "mix_voices": "Mix Voices"
  },
  "comments_header": "Comments",
  "add_comment_hint": "Add a comment...",
  "write_reply_hint": "Write a reply...",
  "view_replies": "View Replies",
  "hide_replies": "Hide Replies",
  "failed_send_reply": "Failed to send reply. Please try again.",
  "reel_audio": "Audio",
  "check_out_reel": "Check out this reel!",
  "reel_saved": "Reel Saved Successfully",
  "reel_unsaved": "Reel UnSaved",
  "use_audio": "Use Audio",
  "audio_load_fail": "Failed to load audio!",
  "no_reels": "No reels",
  "one_reel": "1 reel",
  "multiple_reels": "reels",
  "gift_body": {
    "no_name": "No Name",
    "gift_sent": "Gift Sent",
    "sent_successfully": "has been sent successfully!",
    "amount_deducted": "Amount deducted",
    "insufficient_funds": "Insufficient Funds",
    "insufficient_funds_message": "You do not have enough money in your wallet.",
    "error": "Error",
    "unexpected_error": "Unexpected error!",
    "ok": "OK",
    "charge_wallet": "Charge Wallet",
    "send_a_gift": "Send a gift",
    "recharge": "Recharge"
  },
  "report_nudity": "This content contains explicit nudity and is inappropriate for general audiences.",
  "report_frequent": "Please investigate the frequency of this user's posts.",
  "report_fake": "The content in question is deceptive and should be verified for authenticity.",
  "report_abuse": "The content reported involves abusive language or behavior.",
  "report_hated": "This report concerns content that promotes hate speech or discrimination.",
  "report_illegal": "The content reported is suspected of promoting illegal activities.",
  "report_politics": "Illegal activities are strictly prohibited on our platform.",
  "report_category_nudity": "nudity",
  "report_category_frequent": "frequent",
  "report_category_fake": "fake",
  "report_category_abuse": "abuse",
  "report_category_hated": "hated",
  "report_category_illegal": "illegal",
  "report_category_politics": "politics",
  "spotlight_title": "Spotlight",
  "friends_title": "Friends",
  "following_title": "Following",
  "discover_title": "Discover",
  "spotlight_follow": "Follow +",
  "spotlight_following": "Following",
  "add_story": "Add Story",
  "postSubmitted": "Your post submitted successfully wait for administration approved",
  "imageNotSelected": "Image not selected",
  "randomAppearance": "Random Appearance",
  "messageSuccessfully": "The message has been sent successfully. You will be contacted as soon as possible.",
  "phoneOptional": "Phone (Optional)",
  "TeamHelp": "49Hub Team is ready to help",
  "moneySuccessfully": "The money has been sent successfully.",
  "paymentAddress": "Payment Address",
  "amount": "Amount",
  "bio": "Bio",
  "friendsAndFollowers": "Friends And Followers",
  "maritalStatus": "Marital Status",
  "single": "Single",
  "married": "Married",
  "divorced": "Divorced",
  "widowed": "Widowed",
  "maleUser": "Male",
  "femaleUser": "Female",
  "requests": "Requests",
  "blocked": "Blocked",
  "searchWithName": "Search With Name...",
  "acceptRequestSuccessfully": "Accept Request Successfully.",
  "removeRequestSuccessfully": "Remove Request Successfully.",
  "unFollowSuccessfully": "Unfollow User Successfully.",
  "tagPeople": "Tag People",
  "selectFeeling": "Select Feeling",
  "selectActivity": "Select Activity",
  "user": "User",
  "provider": "Provider",
  "createAd": "Create Ad",
  "title": "Title",
  "desc": "Description",
  "details": "Details",
  "addImages": "Add Images",
  "addImagesDesc": "5MB maximum file size accepted in the following formats: jpg, Jpeg, png, gif",
  "noAds": "There are no Ads at the moment.",
  "write_story": "Write your story...",
  "add_description": "Add a description...",
  "text": "Text",
  "picture": "Picture",
  "create_story": "Create Story",
  "my_contacts": "My contacts",
  "my_contacts_except": "My contacts except...",
  "only_share_with": "Only share with...",
  "status_privacy": "Status Privacy",
  "who_can_see_status": "Who can see my status updates",
  "one_contact": "1 contact",
  "no_contacts_available": "No contacts available",
  "privacy_settings_info": "Changes to your privacy settings will affect all of your statuses.",
  "privacy_settings_help": "Privacy Settings Help",
  "choose_who_can_see_status": "Choose who can see your status updates:",
  "my_contacts_info": "• My contacts: All your contacts can see your status.",
  "my_contacts_except_info": "• My contacts except...: Select contacts who won't see your status.",
  "only_share_with_info": "• Only share with...: Choose specific contacts to share your status.",
  "currency": "L.E",
  "friend": "Friend",
  "view": "View",
  "adTitle": "Ad Title",
  "playedSpins": "Sorry, you have played all your spins for today.",
  "noFavouriteCategory": "There is no favourite category at the moment.",
  "noFavouriteSubCategory": "There is no favourite sub category at the moment.",
  "face": "49 Face",
  "insta": "49 Insta",
  "socialPage": "Social Page",
  "errorLoadingSocialPage": "Error loading social page",
  "updateSuccessfully": "Update Successfully",
  "carpool": "Carpool",
  "paymentOption": "Payment Option",
  "free": "Free",
  "booked": "Booked",
  "inProgress": "In Progress",
  "myBookings": "My Bookings",
  "runningTrips": "Running Trips",
  "welcomeToCarPool": "Welcome To Car Pool",
  "youDontHaveCarMessage": "You don't have a car, You will initiate a route and waiting for one hour to give users time to book a seat in the same car",
  "createRoute": "Create Route",
  "womenDriverOnly": "Women Driver Only",
  "newRoute": "New Route",
  "youWillFindFewerOption": "You will find fewer drivers if you select this option",
  "pleaseUploadVideo": "Please upload Video",
  "pleaseUploadImage": "Please upload Image",
  "expiredTrips": "Expired Trips",
  "expired": "Expired",
  "youDontOwnCar": "You don't own a car/Someone will share the trip with you and pay half price",
  "muted": "Muted",
  "comfort": "Comfort",
  "egp": "EGP",
  "minutesAgo": "Minutes ago",
  "hoursAgo": "Hours ago",
  "daysAgo": "Days ago",
  "womenOnly": "Women only",
  "bookSeat": "Book Seat",
  "pricePerSeat": "Price Per Seat",
  "book": "Book",
  "chance": "Chance",
  "subTab": "Sub Tab",
  "exactly2items": "Please select exactly 2 items.",
  "snap": "Snap",
  "spotlight": "Spotlight",
  "atLeast3atMost5items": "Please select at least 3 and at most 5 items.",
  "editPage": "Edit Page",
  "navigateBar": "Navigate Bar",
  "favoriteCategory": "Favorite Category",
  "customPage": "Custom Page",
  "activatePage": "Activate Page",
  "pagePreview": "Page Preview",
  "service": "Service",
  "atLeast3atMost8items": "Please select at least 3 and at most 8 items.",
  "failedToLoadCategories": "Failed to load categories",
  "nOFoundUsers": "No Found Users",
  "chatWith": "Chat with",
  "Unfollow": "Unfollow",
  "stopSeeing": "Stop seeing posts while keeping him as a friend\"",
  "unblock": "Unblock",
  "youCanRemove": "You can remove",
  "fromBlockedList": "from blocked list",
  "unfriend": "Unfriend",
  "fromFriendsList": "from friends list",
  "shareProfile": "Share Profile",
  "createdOn": "Created On",
  "active": "Active",
  "pending": "Pending",
  "adReviewSoon": "This ad is being reviewed and it will be live soon.",
  "sureRemoveAd": "Are you sure, you want to remove AD?",
  "markSsSold": "Mark as sold",
  "deactivate": "Deactivate",
  "tel": "Tel",
  "chats": "Chats",
  "deleteAd": "Delete",
  "rent": "Rent",
  "sale": "Sale",
  "seat": "Seat",
  "repeated": "Repeated",
  "subscription": "Subscription",
  "tripJoinAds": "Trip Join Ads",
  "adSoldout": "Are you sure, you want to set this AD as soldout?",
  "viewAll": "View All",
  "addACaption": "Add a caption...",
  "and": "And",
  "otherContacts": "Other Contacts",
  "registered": "Registered",
  "add": "Add",
  "noDocs": "No Docs",
  "noLinks": "No Links",
  "noMedia": "No Media",
  "broadcasts": "Broadcasts",
  "myBroadcasts": "My Broadcasts",
  "channelInfo": "Channel Info",
  "unfollow": "Unfollow",
  "receiveFawry": "Your Yellow Card request is successful! 50 has been deducted. You will receive a notification when your card is ready for pickup at any Fawry branch.",
  "doYellowCard": "Do you have a Yellow Card?",
  "yellowCardNumber": "Yellow Card Phone Number",
  "atLeast300YellowCard": "You need at least 300 to request a Yellow Card.",
  "WillBeDeducted": "Request Yellow Card (50 will be deducted)",
  "iDFrontAndBack": "Upload Your ID (Front and Back):",
  "uploadFrontID": "Upload Front ID",
  "frontIDUploaded": "Front ID Uploaded",
  "uploadBackID": "Upload Back ID",
  "BackIDUploaded": "Back ID Uploaded'",
  "pleaseEnterFrontIdAndBackId": "Please enter front id and back id to to continue in request yellow card",
  "submitYellowCardRequest": "Submit Yellow Card Request",
  "Other": "other",
  "pleaseEnterYourPhoneNumber": "Please enter your phone number.",
  "invalidPhoneNumber": "Invalid phone number",
  "successfullyReceiveYourMoneyShortly": "You have successfully submitted your payment check your balance,you will receive your money shortly",
  "chooseInstaPayOption": "Choose InstaPay Option",
  "instaPayAccount": "InstaPay Account",
  "instaPayUsernameOrShortcut": "InstaPay Username or Shortcut",
  "bankAccount": "Bank Account",
  "cardNumber": "Card Number",
  "type": "Type:",
  "account": "Account",
  "bankAccountNumber": "Bank Account Number",
  "pleaseEnterBankAccountNumber": "Please enter a bank account number",
  "pleaseEnter1016digits": "Please enter a valid bank account number (10-16 digits)",
  "bankName": "Bank Name",
  "pleaseEnterBankName": "Please enter a bank name",
  "bankNameCanOnlyContainLetters": "Bank name can only contain letters",
  "pleaseEnterCardNumber": "Please enter a card number",
  "enterNumber16digits": "Please enter a valid card number (16 digits)",
  "invalidCardNumber": "Invalid card number",
  "pleaseEnterUsername": "Please enter a username",
  "usernameContainLettersNumbersUnderscores": "Username can only contain letters, numbers, and underscores",
  "paymentOptions": "Payment Options",
  "enterYourCreditCardDetails": "Enter your credit card details",
  "enterPaymobLink": "Enter your Paymob link",
  "enterBankAccountDetails": "Enter your bank account details",
  "file": "File",
  "enjoyServingClientsUsingCar": "You can enjoy serving your clients using your car by clicking the register button above",
  "tripSuccessfullyClosed": "The trip has been successfully closed",
  "requestSentOffersComingSoon": "Your request has been sent. You'll receive offers shortly",
  "requestSuccessfullyApproved": "The request has been successfully approved",
  "requestSuccessfullyRejected": "The request was successfully rejected",
  "tripCompleted": "Trip is completed",
  "subscribeToContactDriver": "Subscribe to contact to the driver",
  "chooseFavoriteSubCategory": "Choose your favorite sub category!",
  "fillReceiptPoint": "You have to fill your receipt point!",
  "fillDeliveryPoint": "You have to fill your delivery point!",
  "fillTime": "You have to fill your time!",
  "fillDate": "You have to fill your date!",
  "fillDescription": "You have to fill your description!",
  "fillOfferPrice": "You have to fill your offer price!",
  "fillPhone": "You have to fill your phone!",
  "thisFieldIsRequiredWithPeriod": "This field is required.",
  "fillIdExpiryDate": "Fill your id expiry date!",
  "fillDrivingLicenseExpiryDate": "Fill your driving license expiry date!",
  "fillLicenseExpiryDate": "Fill your license expiry date!",
  "fillCarModel": "Fill your car model!",
  "continue": "Continue",
  "enterRoute": "Enter Your route",
  "reportedTrip": "You have reported this trip.",
  "pickupLocation": "Pickup Location",
  "destination": "Destination",
  "pickupTime": "Pickup Time",
  "cargoDescription": "Cargo Description",
  "noPercentageDeductionFromServiceProvider": "The application does not deduct any percentage from the service provider.",
  "premiumPackageMoreVisibilityCashback": "The Premium Package gives you the opportunity to be more visible and get more cashback.",
  "freeCancellation": "Free cancellation",
  "request": "Request",
  "driverDashboard": "Driver dashboard",
  "newBookingsWaiting": "New Bookings are waiting you, go to driver dashboard and explore more!",
  "Call": "Call",
  "Message": "Message",
  "Report": "Report",
  "youCanEnjoyServingYourClientsUsingYourCarByClickingTheRegisterButtonAbove": "You can enjoy serving your clients using your car by clicking the register button above.",
  "theTripHasBeenSuccessfullyClosed": "The trip has been successfully closed.",
  "yourRequest": "Your request",
  "yourRequestHasBeenSentYoullReceiveOffersShortly": "Your request has been sent. You'll receive offers shortly.",
  "theRequestHasBeenSuccessfullyApproved": "The request has been successfully approved.",
  "theRequestWasSuccessfullyRejected": "The request was successfully rejected.",
  "tripIsCompleted": "Trip is completed",
  "newOffer": "New Offer",
  "carModel": "car model",
  "orders": "Orders",
  "completeTrip": "Complete Trip",
  "decline": "Decline",
  "subscribeToContactToTheDriver": "Subscribe to contact to the driver",
  "youHaveToSelectOneSubCategory": "You have to select one sub category!",
  "chooseYourFavoriteSubCategory": "Choose your favorite sub category!",
  "youHaveToFillYourReceiptPoint": "You have to fill your receipt point!",
  "youHaveToFillYourDeliveryPoint": "You have to fill your devlivery point!",
  "youHaveToFillYourTime": "You have to fill your time!",
  "youHaveToFillYourDate": "You have to fill your date!",
  "pickupDate": "Pickup Date",
  "youHaveToFillYourDescription": "You have to fill your description!",
  "youHaveToFillYourOfferPrice": "You have to fill your offer price!",
  "youHaveToFillYourPhone": "You have to fill your phone!",
  "pickupDashboard": "Pickup Dashboard",
  "trips": "Trips",
  "information": "Information",
  "subscribeToSendOfferContactTheClient": "Subscribe to send offer / contact the client",
  "registrationForm": "Registertion Form",
  "deadlineSubscription": "Deadline Subscription",
  "subcategoryName": "Subcateogry name",
  "addSubscription": "Add Subscription",
  "deadlineId": "Deadline Id",
  "deadlineLicense": "Deadline License",
  "deadlineDriverLicense": "Deadline Driver License",
  "yourTrips": "Your Trips",
  "profit": "Profit",
  "clientsRating": "Clients Rating",
  "deleteRegistration": "Delete Registration",
  "successUpdateDriver": "Success update Driver",
  "welcomeToShipRegister": "Welcome to Ship Register",
  "subCategory": "Sub Category",
  "carPicture": "Car Picture",
  "idNumber": "ID Number",
  "plateInformation": "Plate information",
  "drivingLicenseExpiryDate": "Driving License Expiry Date",
  "licenseExpiryDate": "License Expiry Date",
  "update": "Update",
  "completed": "Completed",
  "trip": "Trip",
  "firstNameIsRequired": "First name is required!",
  "lastNameIsRequired": "Last name is required!",
  "phoneIsRequired": "Phone is required!",
  "thisFieldIsRequired": "This field is required!",
  "thisFieldIsRequired2": "This field is required.",
  "fillYourIdExpiryDate": "fill your id expiry date!",
  "fillYourDrivingLicenseExpiryDate": "fill your driving license expiry date!",
  "fillYourLicenseExpiryDate": "fill your license expiry date!",
  "fillYourCarModel": "fill your car model!",
  "rider": "Rider",
  "continueKey": "Continue",
  "selectDropOffLocation": "Select drop off location",
  "selectPickupLocation": "Select Pickup location",
  "enterYourRoute": "Enter Your route",
  "whereToDeliver": "Where to deliver",
  "toAddress": "To Address",
  "entrance": "Entrance",
  "whatToDeliver": "What to deliver",
  "notes": "Notes",
  "offerPrice": "Offer Price",
  "premiumRequest": "Premium Request",
  "normalRequest": "Normal Request",
  "whereToPickUp": "Where to pick up",
  "fromAddress": "From Address",
  "shippingDetails": "Shipping Details",
  "youHaveReportedThisTrip": "you have reported this trip.",
  "newRide": "New Ride",
  "cancelRequest": "Cancel Request",
  "sendOffer": "Send Offer",
  "subscribed": "Subscribed",
  "unsubscribed": "Unsubscribed",
  "seeAll": "See All",
  "idExpiryDate": "ID Expiry Date",
  "licenseFrontAndBack": "Upload Your License (Front and Back)",
  "other": "Others",
  "filter": "Filter",
  "beAStar": "Be A Star",
  "pleaseEnterTheAmount": "Please enter the amount",
  "selectBankName": "Select Bank Name",
  "pleaseSelectPaymentMethod": "Please select a payment method",
  "sureWithdrawMoney": "Are you sure of withdraw money?",
  "requestYellowCard": "Request Yellow Card",
  "deducted": "will be deducted",
  "fullName": "Full Name",
  "pleaseEnterFullName": "Please enter full name",
  "nationalIdNumber": "National Id Number",
  "pleaseEnterNationalId": "Please enter national id",
  "pleaseEnter14Digit": "Please enter 14 digit",
  "yellowCardSuccess": "You have successfully submitted your payment check your yellow card balance.",
  "walletDigital": "You have successfully submitted your payment. Check your inbox, you will receive your money shortly.",
  "notWalletDigital": "You have successfully submitted your payment. Check your inbox, you will receive a voucher including your money shortly.",
  "HaveWallet": "Do you have a wallet?",
  "submitPayment": "Submit Payment",
  "cashOutOption": "Cash out Option",
  "select": "Select",
  "SubscriberCompletionRate": "Subscriber Completion Rate",
  "ChanceDetails": "Chance Details",
  "ProductDescription": "Product Description",
  "Typethevalueyouwanttoparticipation": "Type the value you want to participation",
  "CreateChance ": "Create Chance ",
  "enterPrice": "Enter Price",
  "enterTitle": "Enter Title",
  "enterDescription": "Enter Description",
  "payAtLeast1": "Pay at least 1 EGP and publish your dream product you want to buy!!!",
  "oneUserWillR": "One User will win randomly every month cycle",
  "moreSubscriptionMore": "More subscription more chance!",
  "uploadOneImage": "Upload At Least One Photo!",
  "editMyAds": "Edit ad",
  "requestTripJoin": "Request Trip Join",
  "requestAd": "Request Ad",
  "view_cart": "View Cart",
  "breakfast": "Breakfast",
  "items_count": "Items",
  "restaurantMenu": "Restaurant Menu",
  "noName": "No Name",
  "unknownRestaurant": "Unknown Restaurant",
  "noOrders": "No Orders",
  "noDate": "No Date",
  "noSubscription": "No Subscription",
  "unknownFood": "Unknown Food",
  "your_cart_empty": "Your cart is empty",
  "your_cart": "Your Cart",
  "restaurant_total": "Restaurant Total:",
  "premium_request": "Premium Request",
  "your_phone_number": "Your Phone Number",
  "please_enter_phone_number": "Please enter your phone number",
  "submit_order": "Submit Order",
  "removeFavouriteSuccessfully": "Remove Favourite Ad Successfully",
  "selectValidUser": "User not found or not valid, please select a valid user",
  "notEnoughMoneyWallet": "Not enough money in wallet",
  "transactionSuccessful": "Transaction Successful",
  "yourTransactionWasSuccessful": "Your transaction was successful",
  "transferAmount": "Transfer Amount",
  "inFront": "In Front",
  "behind": "Behind",
  "drivingLicense": "Driving License",
  "theApplicationDoesNotDeductAnyPercentage": "The application does not deduct any percentage from the service provider.",
  "youWillGetPoundsAnnually": "You will get 3,650 pounds annually if you subscribe.",
  "license": "رخصة",
  "snapCopyOfBillPayment": "Snap copy of bill payment",
  "paymentSuccessful": "Payment successful",
  "sendReviewApproval": "Send for review and approval",
  "youWin": "You Win!",
  "shipping": "Shipping",
  "food": "Food",
  "thereNoItems": "There is no items",
  "areDeleteThisAd": "Are you sure you want to delete this Ad!",
  "offers": "Offers",
  "contactPhone": "Contact Phone",
  "booking": "Booking",
  "shareTransactionDetails": "Share Transaction Details",
  "insufficientAmount": "Insufficient Amount",
  "selectAmountToCharge": "Select amount to charge",
  "chargeNow": "Charge Now",
  "premiumSubscription": "Premium Subscription",
  "regularSubscription": "Regular Subscription",
  "mutualFriend": "mutual friend",
  "youWillHidePost": "You Will Hide Post",
  "serveClientsByClickRegister": "Serve Clients By Click Register",
  "expiredRequests": "Expired Requests",
  "notSubscribed": "Not Subscribed",
  "adRequests": "Ad Requests",
  "showAdRequests": "Show Ad Requests",
  "Phonenumbercannotbewrittenindescription": "Phone number cannot be written in description"
};
static const Map<String, Map<String,dynamic>> mapLocales = {"ar": ar, "en": en};
}
