// DO NOT EDIT. This is code generated via package:easy_localization/generate.dart

// ignore_for_file: prefer_single_quotes, avoid_renaming_method_parameters

import 'dart:ui';

import 'package:easy_localization/easy_localization.dart' show AssetLoader;

class CodegenLoader extends AssetLoader{
  const CodegenLoader();

  @override
  Future<Map<String, dynamic>?> load(String path, Locale locale) {
    return Future.value(mapLocales[locale.toString()]);
  }

  static const Map<String,dynamic> ar = {
  "join": "انضم الآن",
  "arabic": "اللغه العربيه",
  "english": "اللغه الانجليزيه",
  "newMeeting": "اجتماع جديد",
  "meal": "اكله",
  "darkMode": "الوضع الداكن",
  "lightMode": "الوضع الفاتح",
  "voice": "صوت",
  "meet": "لقاء",
  "cast": "إرسال",
  "tweet": "تغريدة",
  "reels": "بكرات",
  "chat": "دردشة",
  "find": "ايجاد",
  "live": "مباشر",
  "health": "صحه",
  "ship": "تحميله",
  "ride": "توصيله",
  "lang": "E",
  "search": "بحث",
  "ads": "اعلانات",
  "ad": "اعلان",
  "wallet": "محفظه",
  "gift": "هدايا",
  "balance": "رصيد",
  "pickMe": "وصلني معاك",
  "tripJoin": "جاي معاك",
  "auction": "مزاد",
  "installments": "تقسيط",
  "craft": "حرفه",
  "homeService": "خدمه منزليه",
  "homeEssentials": "مستلزمات منزل",
  "scenery": " ديكور",
  "specialities": "التخصصات",
  "medicalService": "الخدمات الطبية",
  "doctor": "دكتور",
  "doctors": "دكاتره",
  "call": "الاتصال",
  "clinicVisit": "زيارة العيادة",
  "emergency": "الطوارئ",
  "homeVisit": "زيارة منزلية",
  "firstName": "الاسم الأول",
  "phoneNumber": "رقم الهاتف",
  "speciality": "التخصص",
  "address": "العنوان",
  "confirm": "تاكيد",
  "doctorList": "قائمة الأطباء",
  "noDoctorsFound": "لم يتم العثور على أطباء",
  "governorate": "المحافظة",
  "city": "المدينة",
  "emptyFieldNotValid": "حقل فارغ غير صالح",
  "login": "تسجيل الدخول",
  "register": "تسجيل",
  "emailOrPhone": "البريد الإلكتروني أو الهاتف",
  "password": "كلمة المرور",
  "forgetPassword": "نسيت كلمة المرور؟",
  "lastName": "اللقب",
  "gender": "الجنس",
  "code": "رمز الإحالة (اختياري)",
  "female": "أنثى",
  "male": "ذكر",
  "conditions": "الشروط والأحكام",
  "iAcceptAll": "أوافق على جميع",
  "terms": "يرجى قبول الشروط والأحكام للمواصلة.",
  "advertiseYourCompany": "أعلن عن شركتك",
  "quraan": "القرآن الكريم",
  "azkar": "الأذكار",
  "favouriteCategories": "الفئات المفضلة",
  "favouriteSubCategories": "الفئات الفرعية المفضلة",
  "favouriteAds": "الإعلانات المفضلة",
  "requestHistory": " سجل الطلبات",
  "lists": "القوائم",
  "myAds": "إعلاناتي",
  "settings": "الإعدادات",
  "privacy": "الخصوصية",
  "policies": "السياسات",
  "shareApp": "مشاركة التطبيق",
  "contactUs": "اتصل بنا",
  "logout": "تسجيل الخروج",
  "luckyWheel": "عجلة الحظ",
  "feelLucky": "هل تشعر بالحظ؟",
  "restaurants": "مطعم",
  "meals": "وجبات الطعام",
  "message": "رسالة",
  "photo": "صورة",
  "video": "فيديو",
  "openAppSettings": "فتح إعدادات التطبيق",
  "allowAccessToYourCamera": "السماح بالوصول للكاميرا",
  "allowAccessToYourMicrophone": "السماح بالوصول للميكروفون",
  "document": "مستند",
  "camera": "كاميرا",
  "microphone": "ميكروفون",
  "gallery": "المعرض",
  "audio": "الصوت",
  "location": "الموقع",
  "contact": "جهة اتصال",
  "pickPhotoOrVideo": "اختر صورة او فيديو",
  "noRideSubcategories": "لا توجد فئات فرعية",
  "enableNotifications": "تفعيل الإشعارات",
  "changePassword": "تغيير كلمة المرور",
  "disableAccount": "تعطيل الحساب",
  "deleteAccount": "حذف الحساب",
  "alert": "تنبيه!",
  "disable": "هل أنت متأكد من أنك تريد تعطيل حسابك؟",
  "delete": "هل أنت متأكد من أنك تريد حذف حسابك؟",
  "specialAds": "إعلانات خاصة",
  "friends": "الأصدقاء",
  "more": "المزيد",
  "Doctor": "طبيب",
  "loadingDriver": "سائق نقل",
  "Restaurant": "مطعم",
  "driver": "سائق",
  "sureLogout": "هل أنت متأكد أنك تريد تسجيل الخروج؟",
  "no": "لا",
  "welcomeBack": "مرحبًا بعودتك",
  "oTP": "تم إرسال OTP بنجاح",
  "required": "مطلوب",
  "emailFormat": "أدخل تنسيق البريد الإلكتروني الصحيح",
  "email": "البريد الإلكتروني",
  "typeHere": "اكتب هنا",
  "sendOTP": "أرسل OTP",
  "forget": "نسيت كلمة المرور",
  "verify": "التحقق",
  "emailOtp": "إرسال OTP عبر البريد الإلكتروني",
  "verification": "التحقق",
  "notifications": "الإشعارات",
  "checkVerification": "يرجى التحقق من بريدك الإلكتروني لمعرفة رمز التحقق",
  "congratulations": "تهانينا",
  "close": "إغلاق",
  "giftApp": "لقد حصلت على هدية بقيمة 400 جنيه كهدية ترحيبية للتسجيل في تطبيق 49.",
  "clearAll": "حذف الكل",
  "clearNotification": "هل أنت متأكد من أنك تريد مسح جميع الإشعارات؟",
  "clearNoti": "هل أنت متأكد أنك تريد مسح هذا الإشعار؟",
  "ok": "نعم",
  "cancel": "الغاء",
  "save": "حفظ",
  "suscessfullySaved": "تم حفظ البيانات بنجاح"
};
static const Map<String,dynamic> en = {
  "join": "Join",
  "arabic": "Arabic",
  "english": "English",
  "newMeeting": "New Meeting",
  "meal": "Meal",
  "darkMode": "Dark Mode",
  "lightMode": "Light Mode",
  "voice": "Voice",
  "meet": "Meet",
  "cast": "Cast",
  "tweet": "Tweet",
  "reels": "Reels",
  "chat": "Chat",
  "find": "Find",
  "live": "Live",
  "health": "Health",
  "ship": "Ship",
  "ride": "Ride",
  "lang": "ع",
  "search": "Search",
  "ads": "Ads",
  "ad": "Ad",
  "wallet": "Wallet",
  "gift": "Gift",
  "balance": "Balance",
  "pickMe": "Pick Me",
  "tripJoin": "Trip Join",
  "auction": "Auction",
  "installments": "Installments",
  "craft": "Craft",
  "homeService": "Home Service",
  "homeEssentials": "Home Essentials",
  "scenery": "Scenery",
  "specialities": "Specialities",
  "medicalService": "Medical Service",
  "doctor": "Doctor",
  "doctors": "Doctors",
  "call": "Call",
  "clinicVisit": "Clinic Visit",
  "emergency": "Emergency",
  "homeVisit": "Home Visit",
  "firstName": "First Name",
  "phoneNumber": "Phone Number",
  "speciality": "Speciality",
  "address": "Address",
  "confirm": "Confirm",
  "doctorList": "Doctor List",
  "noDoctorsFound": "No doctors found",
  "governorate": "Governorate",
  "city": "City",
  "emptyFieldNotValid": "Empty Field Not Valid",
  "login": "Login",
  "register": "Register",
  "emailOrPhone": "Email Or Phone",
  "password": "Password",
  "forgetPassword": "Forget Password?",
  "lastName": "Last Name",
  "gender": "Gender",
  "code": "Referral Code(Optional)",
  "female": "Female",
  "male": "Male",
  "conditions": "Terms,Rules & Conditions",
  "iAcceptAll": "I Accept All",
  "terms": "Please accept the terms and conditions to continue.",
  "message": "Message",
  "photo": "Photo",
  "video": "Video",
  "advertiseYourCompany": "Advertise Your Company",
  "quraan": "Quraan",
  "azkar": "Azkar",
  "favouriteCategories": "Favourite Categories",
  "favouriteSubCategories": "Favourite Sub Categories",
  "favouriteAds": "Favourite Ads",
  "requestHistory": "Requests History",
  "lists": "Lists",
  "myAds": "My Ads",
  "settings": "Settings",
  "privacy": "Privacy",
  "policies": "Policies",
  "shareApp": "Share App",
  "contactUs": "Contact Us",
  "logout": "Logout",
  "luckyWheel": "Lucky Wheel",
  "feelLucky": "Do You feel lucky?",
  "restaurants": "Restaurants",
  "meals": "Meals",
  "openAppSettings": "Open App Settings",
  "pleaseAllowPermissions": "Please allow permissions",
  "allowAccessToYourCamera": "Allow access to your camera",
  "allowAccessToYourMicrophone": "Allow access to your microphone",
  "document": "Document",
  "camera": "Camera",
  "microphone": "Microphone",
  "gallery": "Gallery",
  "audio": "Audio",
  "location": "Location",
  "contact": "Contact",
  "pickPhotoOrVideo": "Pick Photo Or Video",
  "noRideSubcategories": "No Ride Subcategories",
  "enableNotifications": "Enable Notifications",
  "changePassword": "Change Password",
  "disableAccount": "Disable Account",
  "deleteAccount": "Delete Account",
  "alert": "Alert!",
  "disable": "Are you sure you want to disable your account?",
  "delete": "Are you sure you want to delete your account?",
  "specialAds": "Special Ads",
  "friends": "Friends",
  "more": "More",
  "Doctor": "Doctor",
  "loadingDriver": "Loading Driver",
  "Restaurant": "Restaurant",
  "driver": "Driver",
  "sureLogout": "Are you sure you want to logout?",
  "no": "No",
  "welcomeBack": "Welcome Back",
  "oTP": "OTP Sent successfully",
  "required": "Required",
  "emailFormat": "Enter correct email format",
  "email": "E-mail",
  "typeHere": "Type here",
  "sendOTP": "Send OTP",
  "forget": "Forget Password",
  "verify": "Verify",
  "emailOtp": "Email OTP",
  "verification": "Verification",
  "notifications": "Notifications",
  "checkVerification": "Please check your email to see the verification code ",
  "congratulations": "Congratulations",
  "close": "CLOSE",
  "giftApp": "You got a gift of 400 pounds as a welcome gift for registering on the 49 app.",
  "clearAll": "Clear All",
  "clearNotification": "Are you sure you want to clear all notifications?",
  "clearNoti": "Are you sure you want to clear notifications?",
  "ok": "Ok",
  "cancel": "Cancel",
  "save": "Save",
  "suscessfullySaved": "Successfully Saved"
};
static const Map<String, Map<String,dynamic>> mapLocales = {"ar": ar, "en": en};
}
