import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

import 'package:flutter/widgets.dart';

class Filter {
  final String enName;
  final String arName;
  final ColorFilter? colorFilter;
  final String ffmpegFilter;

  const Filter(this.enName, this.arName, this.colorFilter,
      {required this.ffmpegFilter});
}

class FilterLibrary {
  static List<String> get filterImagesPaths => [
        'assets/filters/1_resized_further_reduced.webp',
        'assets/filters/2_resized_further_reduced.webp',
        'assets/filters/3_resized_further_reduced.webp',
        'assets/filters/4_resized_further_reduced.webp',
        'assets/filters/5_resized_further_reduced.webp',
        'assets/filters/6_further_reduced.png',
        'assets/filters/7_further_reduced.png',
        'assets/filters/8_further_reduced.webp',
        'assets/filters/9_further_reduced.webp',
        'assets/filters/10_further_reduced.webp',
        'assets/filters/11_further_reduced.webp',
        'assets/filters/12_further_reduced.webp',
        'assets/filters/13_further_reduced.webp',
        'assets/filters/14_further_reduced.webp',
        'assets/filters/15_further_reduced.webp',
        'assets/filters/16_further_reduced.webp',
        'assets/filters/17_further_reduced.webp',
      ];

  static List<Filter> get filters => [
        const Filter('Normal', 'عادي', null, ffmpegFilter: ''),
        const Filter(
          'Sepia',
          'سيبيا',
          ColorFilter.matrix([
            0.393,
            0.769,
            0.189,
            0,
            0,
            0.349,
            0.686,
            0.168,
            0,
            0,
            0.272,
            0.534,
            0.131,
            0,
            0,
            0,
            0,
            0,
            1,
            0,
          ]),
          ffmpegFilter:
              'colorchannelmixer=rr=0.393:rg=0.769:rb=0.189:gr=0.349:gg=0.686:gb=0.168:br=0.272:bg=0.534:bb=0.131',
        ),
        const Filter(
          'Grayscale',
          'تدرج رمادي',
          ColorFilter.matrix([
            0.2126,
            0.7152,
            0.0722,
            0,
            0,
            0.2126,
            0.7152,
            0.0722,
            0,
            0,
            0.2126,
            0.7152,
            0.0722,
            0,
            0,
            0,
            0,
            0,
            1,
            0,
          ]),
          ffmpegFilter:
              'colorchannelmixer=rr=0.2126:rg=0.7152:rb=0.0722:gr=0.2126:gg=0.7152:gb=0.0722:br=0.2126:bg=0.7152:bb=0.0722',
        ),
        const Filter(
          'Invert',
          'عكس',
          ColorFilter.matrix([
            -1, 0, 0, 0, 255, // Invert Red
            0, -1, 0, 0, 255, // Invert Green
            0, 0, -1, 0, 255, // Invert Blue
            0, 0, 0, 1, 0, // Alpha (no change)
          ]),
          ffmpegFilter: 'negate',
        ),
        const Filter(
          'Vintage',
          'قديم',
          ColorFilter.matrix([
            0.9,
            0.6,
            0.2,
            0,
            0,
            0.3,
            0.7,
            0.2,
            0,
            0,
            0.2,
            0.3,
            0.8,
            0,
            0,
            0,
            0,
            0,
            1,
            0,
          ]),
          ffmpegFilter:
              'colorchannelmixer=rr=0.9:rg=0.6:rb=0.2:gr=0.3:gg=0.7:gb=0.2:br=0.2:bg=0.3:bb=0.8,curves=vintage',
        ),
        const Filter(
          'Brighten',
          'تفتيح',
          ColorFilter.matrix([
            1.2,
            0,
            0,
            0,
            0,
            0,
            1.2,
            0,
            0,
            0,
            0,
            0,
            1.2,
            0,
            0,
            0,
            0,
            0,
            1,
            0,
          ]),
          ffmpegFilter: 'colorchannelmixer=rr=1.2:gg=1.2:bb=1.2',
        ),
        const Filter(
          'Cool',
          'بارد',
          ColorFilter.matrix([
            1,
            0,
            0,
            0,
            0,
            0,
            1,
            0,
            0,
            0,
            0,
            0,
            1.1,
            0,
            0,
            0,
            0,
            0,
            1,
            0,
          ]),
          ffmpegFilter: 'colorchannelmixer=bb=1.1,colorbalance=bs=0.1',
        ),
        const Filter(
          'Warm',
          'دافئ',
          ColorFilter.matrix([
            1.1,
            0,
            0,
            0,
            0,
            0,
            1,
            0,
            0,
            0,
            0,
            0,
            0.9,
            0,
            0,
            0,
            0,
            0,
            1,
            0,
          ]),
          ffmpegFilter: 'colorchannelmixer=rr=1.1:bb=0.9,colorbalance=rs=0.1',
        ),
        const Filter(
          'Soft Glow',
          'توهج ناعم',
          ColorFilter.matrix([
            1.2,
            0,
            0,
            0,
            0,
            0,
            1.2,
            0,
            0,
            0,
            0,
            0,
            1.2,
            0,
            0,
            0,
            0,
            0,
            1,
            0,
          ]),
          ffmpegFilter:
              'colorchannelmixer=rr=1.2:gg=1.2:bb=1.2,gblur=sigma=0.5',
        ),
        const Filter(
          'Dreamy',
          'حالِم',
          ColorFilter.matrix([
            0.9,
            0,
            0,
            0,
            0,
            0,
            0.9,
            0,
            0,
            0,
            0,
            0,
            0.9,
            0,
            0,
            0,
            0,
            0,
            1,
            0.1,
          ]),
          ffmpegFilter:
              'colorchannelmixer=rr=0.9:gg=0.9:bb=0.9,gblur=sigma=1:steps=2',
        ),
        const Filter(
          'Pink Haze',
          'ضباب وردي',
          ColorFilter.matrix([
            1.2,
            0,
            0,
            0,
            0,
            0,
            1.1,
            0,
            0,
            0,
            0,
            0,
            1.1,
            0,
            0,
            0,
            0,
            0,
            1,
            0,
          ]),
          ffmpegFilter:
              'colorchannelmixer=rr=1.2:gg=1.1:bb=1.1,colorbalance=rm=0.1:bm=0.1',
        ),
        const Filter(
          'Steel Blue',
          'أزرق فولاذي',
          ColorFilter.matrix([
            1,
            0,
            0,
            0,
            0,
            0,
            1,
            0,
            0,
            0,
            0,
            0,
            1.2,
            0,
            0,
            0,
            0,
            0,
            1,
            0,
          ]),
          ffmpegFilter: 'colorchannelmixer=bb=1.2,colorbalance=bs=0.1',
        ),
        const Filter(
          'Rustic',
          'ريفي',
          ColorFilter.matrix([
            0.9,
            0.1,
            0,
            0,
            0,
            0.1,
            0.8,
            0.1,
            0,
            0,
            0,
            0.1,
            0.9,
            0,
            0,
            0,
            0,
            0,
            1,
            0,
          ]),
          ffmpegFilter:
              'colorchannelmixer=rr=0.9:rg=0.1:gr=0.1:gg=0.8:gb=0.1:bg=0.1:bb=0.9,curves=strong_contrast',
        ),
        const Filter(
          'Noir',
          'نوير',
          ColorFilter.matrix([
            0.3,
            0.3,
            0.3,
            0,
            0,
            0.3,
            0.3,
            0.3,
            0,
            0,
            0.3,
            0.3,
            0.3,
            0,
            0,
            0,
            0,
            0,
            1,
            0,
          ]),
          ffmpegFilter:
              'colorchannelmixer=rr=0.3:rg=0.3:rb=0.3:gr=0.3:gg=0.3:gb=0.3:br=0.3:bg=0.3:bb=0.3',
        ),
        const Filter(
          'Psychedelic',
          'مخدر',
          ColorFilter.matrix([
            0.5,
            0.5,
            0,
            0,
            0,
            0.5,
            0,
            0.5,
            0,
            0,
            0,
            0.5,
            0.5,
            0,
            0,
            0,
            0,
            0,
            1,
            0,
          ]),
          ffmpegFilter:
              'colorchannelmixer=rr=0.5:rg=0.5:gr=0.5:gb=0.5:br=0:bg=0.5:bb=0.5,hue=h=60:s=3',
        ),
        const Filter(
          'Neon Glow',
          'توهج النيون',
          ColorFilter.matrix([
            1.5,
            0,
            0,
            0,
            0,
            0,
            1.5,
            0,
            0,
            0,
            0,
            0,
            1.5,
            0,
            0,
            0,
            0,
            0,
            1,
            0,
          ]),
          ffmpegFilter: 'colorchannelmixer=rr=1.5:gg=1.5:bb=1.5',
        ),
        const Filter(
          'Retro',
          'ريترو',
          ColorFilter.matrix([
            1.0,
            0.4,
            0.4,
            0,
            0,
            0.4,
            1.0,
            0.4,
            0,
            0,
            0.4,
            0.4,
            1.0,
            0,
            0,
            0,
            0,
            0,
            1,
            0,
          ]),
          ffmpegFilter:
              'colorchannelmixer=rr=1.0:rg=0.4:rb=0.4:gr=0.4:gg=1.0:gb=0.4:br=0.4:bg=0.4:bb=1.0,curves=vintage,vignette',
        ),
      ];
}
